In [4]:
import sys 
import numpy as np
import pandas as pd
import statsmodels.api as sm
import sklearn
import scipy as sp
%matplotlib inline 
import matplotlib.pyplot as plt

In [5]:
des_vars = pd.read_stata("oregonhie_descriptive_vars.dta")
des_vars.head()

,person_id,household_id,treatment,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,...,birthyear_list,have_phone_list,english_list,female_list,first_day_list,last_day_list,pobox_list,self_list,week_list,zip_msa_list
0,1.0,100001.0,Selected,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,No,2008-08-12,2008-09-08,2008-12-31,...,1978,Gave Phone Number,Requested English materials,0: Male,Did NOT sign up for lottery list on first day,Did NOT sign up for lottery list on last day,1: POBOX,Signed self up,Week 2,Zip code of residence in a MSA
1,2.0,100002.0,Selected,Draw 6: selected in lottery 07/01/2008,Lottery Draw 6,Did NOT submit an application to OHP,No,2008-07-14,2008-08-08,NaT,...,1984,Gave Phone Number,Requested English materials,1: Female,Did NOT sign up for lottery list on first day,Did NOT sign up for lottery list on last day,0: Not POBOX,Signed self up,Week 3,Zip code of residence in a MSA
2,3.0,100003.0,Not selected,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,...,1971,Gave Phone Number,Requested English materials,1: Female,Did NOT sign up for lottery list on first day,Did NOT sign up for lottery list on last day,0: Not POBOX,Signed self up,Week 3,Zip code of residence in a MSA
3,4.0,100004.0,Not selected,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,...,1955,Gave Phone Number,Requested English materials,1: Female,Did NOT sign up for lottery list on first day,Did NOT sign up for lottery list on last day,0: Not POBOX,Signed self up,Week 1,Zip code of residence in a MSA
4,5.0,100005.0,Selected,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,...,1969,Gave Phone Number,Requested materials in language other than eng...,1: Female,Did NOT sign up for lottery list on first day,Did NOT sign up for lottery list on last day,0: Not POBOX,Signed self up,Week 2,Zip code of residence in a MSA

In [6]:
ed_vars = pd.read_stata("oregonhie_ed_vars.dta")
ed_vars.head()

,person_id,sample_ed,any_visit_pre_ed,any_visit_ed,num_visit_pre_cens_ed,num_visit_cens_ed,any_hosp_pre_ed,any_hosp_ed,num_hosp_pre_cens_ed,num_hosp_cens_ed,...,ed_charg_tot_pre_ed,ed_charg_tot_ed,any_hiun_pre_ed,any_hiun_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed
0,60562.0,1.0,No,No,0.0,0.0,No,No,0.0,0.0,...,0.0,0.000000,No,No,0.0,0.0,No,No,0.0,0.0
1,51142.0,1.0,No,Yes,0.0,3.0,No,No,0.0,0.0,...,0.0,2220.699951,No,Yes,0.0,3.0,No,No,0.0,0.0
2,60314.0,1.0,No,Yes,0.0,2.0,No,Yes,0.0,1.0,...,0.0,4529.549805,No,Yes,0.0,2.0,No,No,0.0,0.0
3,50902.0,1.0,No,No,0.0,0.0,No,No,0.0,0.0,...,0.0,0.000000,No,No,0.0,0.0,No,No,0.0,0.0
4,70733.0,1.0,No,No,0.0,0.0,No,No,0.0,0.0,...,0.0,0.000000,No,No,0.0,0.0,No,No,0.0,0.0

In [7]:
inperson_vars = pd.read_stata("oregonhie_inperson_vars.dta")
inperson_vars.head()

,person_id,in_data_inp,sample_resp_inp,weight_total_inp,dt_release_inp,dt_completed_inp,interview_location_inp,interviewer_inp,scale_id_inp,stadio_id_inp,...,has_hght_wght_inp,has_dbs_inp,has_all_dbs_inp,rx_any_mod_inp,rx_num_mod_inp,hbp_diure_med_inp,antihyperlip_med_inp,diabetes_med_inp,antidep_med_inp,meds_miss_inp
0,45656.0,Yes,Non Respondent,3.208729,2010-05-17,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,65912.0,Yes,Respondent,1.150416,2009-11-30,2009-12-15,2: Portland West,48.0,SV408,SV208,...,Yes,Yes,Yes,Yes,1.0,No,No,No,No,No
2,37139.0,Yes,Respondent,1.003278,2010-03-09,2010-04-07,2: Portland West,28.0,SV408,SV208,...,Yes,Yes,Yes,Yes,2.0,No,No,No,Yes,No
3,64670.0,Yes,Respondent,1.159381,2010-01-13,2010-01-19,1: Portland East,6.0,PK414,Other,...,Yes,Yes,Yes,No,0.0,No,No,No,No,No
4,65225.0,Yes,Non Respondent,0.000000,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
patterns_vars = pd.read_stata("oregonhie_patterns_vars.dta")
patterns_vars.head()

,person_id,household_id,any_visit_180p_180,any_visit_180p_360,any_visit_180p_540,any_visit_180p_720,preperiod_any_visits,medicaid_all_180p_period_180,medicaid_all_180p_period_360,medicaid_all_180p_period_540,...,pobox_list,first_day_list,self_list,ohp_all_ever_inperson,dt_completed_inp,weight_total_inp,sample_inp_resp,doc_any_incl_probe_inp,ed_any_incl_probe_inp,any_inp_match_ed
0,8218.0,108218.0,No,No,Yes,No,No,Yes,Yes,Yes,...,0: Not POBOX,Signed up for lottery list on first day,Signed self up,NOT enrolled,NaT,NaN,NaN,NaN,NaN,NaN
1,62755.0,162755.0,No,Yes,Yes,No,Yes,No,No,No,...,0: Not POBOX,Signed up for lottery list on first day,Signed self up,NOT enrolled,NaT,NaN,NaN,NaN,NaN,NaN
2,27528.0,127528.0,No,No,No,No,Yes,No,No,No,...,0: Not POBOX,Signed up for lottery list on first day,Signed self up,NOT enrolled,NaT,NaN,NaN,NaN,NaN,NaN
3,67031.0,167031.0,No,No,No,No,Yes,No,No,No,...,0: Not POBOX,Signed up for lottery list on first day,Signed self up,NOT enrolled,NaT,NaN,NaN,NaN,NaN,NaN
4,45656.0,145656.0,No,Yes,No,No,Yes,No,No,No,...,0: Not POBOX,Signed up for lottery list on first day,Signed self up,NOT enrolled,NaT,3.208729,Non Respondent,NaN,NaN,NaN

In [9]:
stateprograms_vars = pd.read_stata("oregonhie_stateprograms_vars.dta")
stateprograms_vars.head()

,person_id,ohp_all_ever_matchn_30sep2009,ohp_all_ever_firstn_survey0m,ohp_all_ever_firstn_survey6m,ohp_all_ever_inperson,ohp_all_ever_firstn_30sep2009,ohp_all_end_30sep2009,ohp_all_end_survey0m,ohp_all_end_survey6m,ohp_all_end_inperson,...,snap_tot_hh_30sep2009,snap_tot_hh_firstn_survey12m,tanf_ever_prenotify07,tanf_ever_presurvey12m,tanf_ever_matchn_30sep2009,tanf_ever_firstn_survey12m,tanf_tot_hh_prenotify07,tanf_tot_hh_presurvey12m,tanf_tot_hh_30sep2009,tanf_tot_hh_firstn_survey12m
0,1.0,NOT enrolled,NOT enrolled,NaN,NaN,NOT enrolled,NOT enrolled,NOT enrolled,NaN,NaN,...,746,2624.0,No,No,No,No,0.0,0.0,0.0,0.0
1,2.0,Enrolled,Enrolled,NaN,NaN,Enrolled,NOT enrolled,Enrolled,NaN,NaN,...,3962,5154.0,No,No,No,No,0.0,0.0,0.0,0.0
2,3.0,NOT enrolled,NOT enrolled,NaN,NaN,NOT enrolled,NOT enrolled,NOT enrolled,NaN,NaN,...,3212,3374.0,No,No,No,No,0.0,0.0,0.0,0.0
3,4.0,Enrolled,NaN,NaN,NaN,Enrolled,Enrolled,NaN,NaN,NaN,...,1260,NaN,No,NaN,No,NaN,0.0,NaN,0.0,NaN
4,5.0,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,NOT enrolled,...,0,0.0,No,No,No,No,0.0,0.0,0.0,0.0

In [7]:
survey0m_vars = pd.read_stata("oregonhie_survey0m_vars.dta")
survey0m_vars.head()

,person_id,sample_0m,wave_survey0m,dt_mail_0m,returned_0m,dt_returned_0m,ret_mode_0m,surv_lang_0m,in_survey_0m,app_received_0m,...,race_other_qn_0m,employ_hrs_0m,edu_0m,living_arrange_0m,hhsize_0m,hhinc_pctfpl_0m,num19_0m,num19_hi_0m,cost_tot_oop_correct_0m,cost_medical_oop_0m
0,1.0,In 0m mail survey sample,Survey Draw 6,2008-08-21,No,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,In 0m mail survey sample,Survey Draw 6,2008-08-21,No,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,In 0m mail survey sample,Survey Draw 4,2008-07-23,No,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,NOT in 0m mail survey sample,NaN,NaT,NaN,NaT,,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,In 0m mail survey sample,Survey Draw 7,2008-09-07,No,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
survey6m_vars = pd.read_stata("oregonhie_survey6m_vars.dta")
survey6m_vars.head()

,person_id,sample_6m,wave_survey6m,dt_mail_6m,returned_6m,dt_returned_6m,ret_mode_6m,surv_lang_6m,in_survey_6m,weight_6m,...,live_partner_6m,live_alone_6m,live_parents_6m,live_relatives_6m,live_friends_6m,live_other_6m,hhsize_6m,hhinc_pctfpl_6m,num19_6m,num19_hi_6m
0,1.0,NOT in 6m mail survey sample,Survey Draw 6,NaT,NaN,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,NOT in 6m mail survey sample,Survey Draw 6,NaT,NaN,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,NOT in 6m mail survey sample,Survey Draw 4,NaT,NaN,NaT,,,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,NOT in 6m mail survey sample,NaN,NaT,NaN,NaT,,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,In 6m mail survey sample,Survey Draw 7,2009-03-02,Yes,2009-03-09,Mail,Spanish,Yes,1.248947,...,Yes,No,No,No,No,Yes,3.0,NaN,0.0,NaN

In [9]:
survey12m_vars = pd.read_stata("oregonhie_survey12m_vars.dta")
survey12m_vars.head()

,person_id,sample_12m,dt_mail_12m,dt_returned_12m,ret_mode_12m,returned_12m,surv_lang_12m,in_survey_12m,sample_12m_resp,sample_12m_nonresp,...,live_alone_12m,live_parents_12m,live_relatives_12m,live_friends_12m,live_other_12m,hhsize_12m,num19_12m,needmet_med_cor_12m,needmet_rx_cor_12m,needmet_dent_cor_12m
0,1.0,In 12m mail survey sample,2009-08-11,2009-11-24,Mail,Yes,English,Yes,12m mail survey responder,NOT a 12m mail survey nonresponder,...,No,Yes,No,No,No,3.0,0.0,No,No,No
1,2.0,In 12m mail survey sample,2009-08-11,2009-08-31,Mail,Yes,English,Yes,12m mail survey responder,NOT a 12m mail survey nonresponder,...,No,No,Yes,No,No,2.0,1.0,No,No,No
2,3.0,In 12m mail survey sample,2009-08-03,NaT,,No,,No,NOT a 12m mail survey responder,NOT a 12m mail survey nonresponder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,NOT in 12m mail survey sample,NaT,NaT,,NaN,,NaN,NOT a 12m mail survey responder,NOT a 12m mail survey nonresponder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,In 12m mail survey sample,2009-08-14,2009-08-21,Mail,Yes,Spanish,Yes,12m mail survey responder,NOT a 12m mail survey nonresponder,...,No,No,No,No,No,3.0,NaN,Yes,Yes,No

In [10]:
ed_sample = pd.merge(des_vars, ed_vars, how='inner', on='person_id')
ed_sample.head()

,person_id,household_id,treatment,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,...,ed_charg_tot_pre_ed,ed_charg_tot_ed,any_hiun_pre_ed,any_hiun_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed
0,5.0,100005.0,Selected,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,...,0.000000,0.000000,No,No,0.0,0.0,No,No,0.0,0.0
1,8.0,102094.0,Not selected,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,...,0.000000,2751.449951,No,Yes,0.0,2.0,No,No,0.0,0.0
2,9.0,100009.0,Not selected,NaN,Lottery Draw 1,NaN,NaN,2008-03-10,2008-03-11,NaT,...,789.500000,0.000000,Yes,No,1.0,0.0,No,No,0.0,0.0
3,16.0,140688.0,Not selected,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,...,1888.199951,7100.799805,Yes,Yes,1.0,5.0,No,No,0.0,0.0
4,18.0,100018.0,Not selected,NaN,Lottery Draw 4,NaN,NaN,2008-05-09,2008-06-09,NaT,...,1006.349976,0.000000,No,No,0.0,0.0,Yes,No,2.0,0.0

In [11]:
ed_sample.describe()

,person_id,household_id,birthyear_list,sample_ed,num_visit_pre_cens_ed,num_visit_cens_ed,num_hosp_pre_cens_ed,num_hosp_cens_ed,num_out_pre_cens_ed,num_out_cens_ed,...,any_inp_match_ed,num_inp_match_ed,charg_tot_pre_ed,charg_tot_ed,ed_charg_tot_pre_ed,ed_charg_tot_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,num_loun_pre_cens_ed,num_loun_cens_ed
count,24646.000000,24646.000000,24646.000000,24646.0,24634.000000,24622.000000,24644.000000,24644.000000,24634.000000,24622.000000,...,10178.000000,10173.000000,24637.000000,24630.000000,24630.000000,24629.000000,24635.000000,24626.000000,24643.000000,24643.000000
mean,37523.394531,140038.062500,1968.398604,1.0,0.774133,0.997319,0.088906,0.114592,0.685638,0.885062,...,0.275889,0.679052,2209.639160,3545.799805,894.847473,1417.405640,0.448914,0.581012,0.329465,0.426166
std,21582.712891,21408.957031,12.045319,0.0,1.863161,2.410316,0.414758,0.525128,1.713480,2.205885,...,0.446999,1.913942,9355.306641,14782.382812,2593.575684,4156.400391,1.291741,1.628780,1.074567,1.369972
min,5.000000,100005.000000,1945.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18787.250000,122045.250000,1958.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,37602.500000,141328.000000,1969.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,56218.750000,158785.000000,1979.000000,1.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,666.650024,1200.822510,542.474976,974.349976,0.000000,0.000000,0.000000,0.000000
max,74920.000000,174920.000000,1988.000000,1.0,17.000000,22.000000,6.000000,7.000000,16.000000,21.000000,...,1.000000,33.000000,183077.375000,280552.375000,42315.648438,71156.687500,13.000000,16.000000,12.000000,14.000000

In [12]:
col = list(ed_sample.columns.values)
col

['person_id',
 'household_id',
 'treatment',
 'draw_treat',
 'draw_lottery',
 'applied_app',
 'approved_app',
 'dt_notify_lottery',
 'dt_retro_coverage',
 'dt_app_decision',
 'postn_death',
 'numhh_list',
 'birthyear_list',
 'have_phone_list',
 'english_list',
 'female_list',
 'first_day_list',
 'last_day_list',
 'pobox_list',
 'self_list',
 'week_list',
 'zip_msa_list',
 'sample_ed',
 'any_visit_pre_ed',
 'any_visit_ed',
 'num_visit_pre_cens_ed',
 'num_visit_cens_ed',
 'any_hosp_pre_ed',
 'any_hosp_ed',
 'num_hosp_pre_cens_ed',
 'num_hosp_cens_ed',
 'any_out_pre_ed',
 'any_out_ed',
 'num_out_pre_cens_ed',
 'num_out_cens_ed',
 'any_on_pre_ed',
 'any_on_ed',
 'num_on_pre_cens_ed',
 'num_on_cens_ed',
 'any_off_pre_ed',
 'any_off_ed',
 'num_off_pre_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_pre_ed',
 'num_edcnnp_ed',
 'num_edcnpa_pre_ed',
 'num_edcnpa_ed',
 'num_epct_pre_ed',
 'num_epct_ed',
 'num_ne_pre_ed',
 'num_ne_ed',
 'num_unclas_pre_ed',
 'num_unclas_ed',
 'any_acsc_pre_ed',
 'any_acsc_ed',
 'num_acsc_pre_cens_ed',
 'num_acsc_cens_ed',
 'any_chron_pre_ed',
 'any_chron_ed',
 'num_chron_pre_cens_ed',
 'num_chron_cens_ed',
 'any_inj_pre_ed',
 'any_inj_ed',
 'num_inj_pre_cens_ed',
 'num_inj_cens_ed',
 'any_skin_pre_ed',
 'any_skin_ed',
 'num_skin_pre_cens_ed',
 'num_skin_cens_ed',
 'any_abdo_pre_ed',
 'any_abdo_ed',
 'num_abdo_pre_cens_ed',
 'num_abdo_cens_ed',
 'any_back_pre_ed',
 'any_back_ed',
 'num_back_pre_cens_ed',
 'num_back_cens_ed',
 'any_heart_pre_ed',
 'any_heart_ed',
 'num_heart_pre_cens_ed',
 'num_heart_cens_ed',
 'any_head_pre_ed',
 'any_head_ed',
 'num_head_pre_cens_ed',
 'num_head_cens_ed',
 'any_depres_pre_ed',
 'any_depres_ed',
 'num_depres_pre_cens_ed',
 'num_depres_cens_ed',
 'any_psysub_pre_ed',
 'any_psysub_ed',
 'num_psysub_pre_cens_ed',
 'num_psysub_cens_ed',
 'any_mail_match_ed',
 'num_mail_match_ed',
 'any_inp_match_ed',
 'num_inp_match_ed',
 'charg_tot_pre_ed',
 'charg_tot_ed',
 'ed_charg_tot_pre_ed',
 'ed_charg_tot_ed',
 'any_hiun_pre_ed',
 'any_hiun_ed',
 'num_hiun_pre_cens_ed',
 'num_hiun_cens_ed',
 'any_loun_pre_ed',
 'any_loun_ed',
 'num_loun_pre_cens_ed',
 'num_loun_cens_ed']

In [11]:
ed_sample = pd.get_dummies(ed_sample, columns = ['treatment','english_list','first_day_list','have_phone_list','pobox_list','self_list'], drop_first = True)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,...,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed,treatment_Selected,english_list_Requested English materials,first_day_list_Signed up for lottery list on first day,have_phone_list_Gave Phone Number,pobox_list_1: POBOX,self_list_Signed self up
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,Alive,...,No,No,0.0,0.0,1,0,0,1,0,1
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,Alive,...,No,No,0.0,0.0,0,1,0,1,0,1
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,NaN,2008-03-10,2008-03-11,NaT,Alive,...,No,No,0.0,0.0,0,1,0,1,0,1
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,Alive,...,No,No,0.0,0.0,0,1,0,1,0,1
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,NaN,2008-05-09,2008-06-09,NaT,Alive,...,Yes,No,2.0,0.0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,No,2008-04-16,2008-05-08,2008-07-18,Alive,...,No,No,0.0,0.0,1,1,0,1,0,1
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,No,2008-08-12,2008-09-08,2008-12-01,Alive,...,No,No,0.0,0.0,1,1,1,1,1,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,Yes,2008-09-11,2008-10-08,2008-11-17,Alive,...,No,No,0.0,0.0,1,0,1,1,1,1
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,NaN,2008-07-14,2008-08-08,NaT,Alive,...,No,Yes,0.0,1.0,0,1,0,1,0,1
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,NaN,2008-07-14,2008-08-08,NaT,Alive,...,No,No,0.0,0.0,0,1,0,1,0,1

In [12]:
ed_sample = pd.get_dummies(ed_sample, columns = ['female_list'], drop_first = True)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,...,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed,treatment_Selected,english_list_Requested English materials,first_day_list_Signed up for lottery list on first day,have_phone_list_Gave Phone Number,pobox_list_1: POBOX,self_list_Signed self up,female_list_1: Female
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,Alive,...,No,0.0,0.0,1,0,0,1,0,1,1
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,Alive,...,No,0.0,0.0,0,1,0,1,0,1,0
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,NaN,2008-03-10,2008-03-11,NaT,Alive,...,No,0.0,0.0,0,1,0,1,0,1,1
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,Alive,...,No,0.0,0.0,0,1,0,1,0,1,1
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,NaN,2008-05-09,2008-06-09,NaT,Alive,...,No,2.0,0.0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,No,2008-04-16,2008-05-08,2008-07-18,Alive,...,No,0.0,0.0,1,1,0,1,0,1,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,No,2008-08-12,2008-09-08,2008-12-01,Alive,...,No,0.0,0.0,1,1,1,1,1,0,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,Yes,2008-09-11,2008-10-08,2008-11-17,Alive,...,No,0.0,0.0,1,0,1,1,1,1,1
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,NaN,2008-07-14,2008-08-08,NaT,Alive,...,Yes,0.0,1.0,0,1,0,1,0,1,0
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,NaN,2008-07-14,2008-08-08,NaT,Alive,...,No,0.0,0.0,0,1,0,1,0,1,1

In [13]:
ed_sample = pd.get_dummies(ed_sample, columns = ['approved_app'], drop_first = True)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,num_loun_pre_cens_ed,num_loun_cens_ed,treatment_Selected,english_list_Requested English materials,first_day_list_Signed up for lottery list on first day,have_phone_list_Gave Phone Number,pobox_list_1: POBOX,self_list_Signed self up,female_list_1: Female,approved_app_Yes
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0.0,0.0,1,0,0,1,0,1,1,0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,0.0,0.0,0,1,0,1,0,1,0,0
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0.0,0.0,0,1,0,1,0,1,1,0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,0.0,0.0,0,1,0,1,0,1,1,0
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,2.0,0.0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0.0,0.0,1,1,0,1,0,1,0,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0.0,0.0,1,1,1,1,1,0,0,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,0.0,0.0,1,0,1,1,1,1,1,1
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0.0,1.0,0,1,0,1,0,1,0,0
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0.0,0.0,0,1,0,1,0,1,1,0

In [14]:
ed_sample = pd.merge(ed_sample, stateprograms_vars, how='inner', on='person_id')
ed_sample.head()

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,snap_tot_hh_30sep2009,snap_tot_hh_firstn_survey12m,tanf_ever_prenotify07,tanf_ever_presurvey12m,tanf_ever_matchn_30sep2009,tanf_ever_firstn_survey12m,tanf_tot_hh_prenotify07,tanf_tot_hh_presurvey12m,tanf_tot_hh_30sep2009,tanf_tot_hh_firstn_survey12m
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0,0.0,No,No,No,No,0.0,0.0,0.0,0.0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,3363,4439.0,No,No,No,No,0.0,0.0,0.0,0.0
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0,0.0,No,No,No,No,0.0,0.0,0.0,0.0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,6433,6997.0,No,No,No,No,0.0,0.0,0.0,0.0
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,3047,3371.0,No,No,No,No,0.0,0.0,0.0,0.0

In [15]:
ed_sample = pd.get_dummies(ed_sample, columns = ['ohp_all_ever_matchn_30sep2009'], drop_first = True)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,snap_tot_hh_firstn_survey12m,tanf_ever_prenotify07,tanf_ever_presurvey12m,tanf_ever_matchn_30sep2009,tanf_ever_firstn_survey12m,tanf_tot_hh_prenotify07,tanf_tot_hh_presurvey12m,tanf_tot_hh_30sep2009,tanf_tot_hh_firstn_survey12m,ohp_all_ever_matchn_30sep2009_Enrolled
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0.0,No,No,No,No,0.0,0.0,0.0,0.0,0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,4439.0,No,No,No,No,0.0,0.0,0.0,0.0,0
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0.0,No,No,No,No,0.0,0.0,0.0,0.0,0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,6997.0,No,No,No,No,0.0,0.0,0.0,0.0,1
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,3371.0,No,No,No,No,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0.0,No,No,No,No,0.0,0.0,0.0,0.0,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0.0,No,No,No,No,0.0,0.0,0.0,0.0,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,4369.0,No,No,No,No,0.0,0.0,0.0,0.0,1
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,NaN,No,NaN,No,NaN,0.0,NaN,0.0,NaN,0
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,NaN,No,NaN,No,NaN,0.0,NaN,0.0,NaN,1

In [18]:
columns = list(ed_sample.columns.values)
columns

['person_id',
 'household_id',
 'draw_treat',
 'draw_lottery',
 'applied_app',
 'dt_notify_lottery',
 'dt_retro_coverage',
 'dt_app_decision',
 'postn_death',
 'numhh_list',
 'birthyear_list',
 'last_day_list',
 'week_list',
 'zip_msa_list',
 'sample_ed',
 'any_visit_pre_ed',
 'any_visit_ed',
 'num_visit_pre_cens_ed',
 'num_visit_cens_ed',
 'any_hosp_pre_ed',
 'any_hosp_ed',
 'num_hosp_pre_cens_ed',
 'num_hosp_cens_ed',
 'any_out_pre_ed',
 'any_out_ed',
 'num_out_pre_cens_ed',
 'num_out_cens_ed',
 'any_on_pre_ed',
 'any_on_ed',
 'num_on_pre_cens_ed',
 'num_on_cens_ed',
 'any_off_pre_ed',
 'any_off_ed',
 'num_off_pre_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_pre_ed',
 'num_edcnnp_ed',
 'num_edcnpa_pre_ed',
 'num_edcnpa_ed',
 'num_epct_pre_ed',
 'num_epct_ed',
 'num_ne_pre_ed',
 'num_ne_ed',
 'num_unclas_pre_ed',
 'num_unclas_ed',
 'any_acsc_pre_ed',
 'any_acsc_ed',
 'num_acsc_pre_cens_ed',
 'num_acsc_cens_ed',
 'any_chron_pre_ed',
 'any_chron_ed',
 'num_chron_pre_cens_ed',
 'num_chron_cens_ed',
 'any_inj_pre_ed',
 'any_inj_ed',
 'num_inj_pre_cens_ed',
 'num_inj_cens_ed',
 'any_skin_pre_ed',
 'any_skin_ed',
 'num_skin_pre_cens_ed',
 'num_skin_cens_ed',
 'any_abdo_pre_ed',
 'any_abdo_ed',
 'num_abdo_pre_cens_ed',
 'num_abdo_cens_ed',
 'any_back_pre_ed',
 'any_back_ed',
 'num_back_pre_cens_ed',
 'num_back_cens_ed',
 'any_heart_pre_ed',
 'any_heart_ed',
 'num_heart_pre_cens_ed',
 'num_heart_cens_ed',
 'any_head_pre_ed',
 'any_head_ed',
 'num_head_pre_cens_ed',
 'num_head_cens_ed',
 'any_depres_pre_ed',
 'any_depres_ed',
 'num_depres_pre_cens_ed',
 'num_depres_cens_ed',
 'any_psysub_pre_ed',
 'any_psysub_ed',
 'num_psysub_pre_cens_ed',
 'num_psysub_cens_ed',
 'any_mail_match_ed',
 'num_mail_match_ed',
 'any_inp_match_ed',
 'num_inp_match_ed',
 'charg_tot_pre_ed',
 'charg_tot_ed',
 'ed_charg_tot_pre_ed',
 'ed_charg_tot_ed',
 'any_hiun_pre_ed',
 'any_hiun_ed',
 'num_hiun_pre_cens_ed',
 'num_hiun_cens_ed',
 'any_loun_pre_ed',
 'any_loun_ed',
 'num_loun_pre_cens_ed',
 'num_loun_cens_ed',
 'treatment_Selected',
 'english_list_Requested English materials',
 'first_day_list_Signed up for lottery list on first day',
 'have_phone_list_Gave Phone Number',
 'pobox_list_1: POBOX',
 'self_list_Signed self up',
 'female_list_1: Female',
 'approved_app_Yes',
 'ohp_all_ever_firstn_survey0m',
 'ohp_all_ever_firstn_survey6m',
 'ohp_all_ever_inperson',
 'ohp_all_ever_firstn_30sep2009',
 'ohp_all_end_30sep2009',
 'ohp_all_end_survey0m',
 'ohp_all_end_survey6m',
 'ohp_all_end_inperson',
 'ohp_all_at_12m',
 'ohp_all_mo_matchn_30sep2009',
 'ohp_all_mo_firstn_survey0m',
 'ohp_all_mo_firstn_survey6m',
 'ohp_all_mo_inperson',
 'ohp_all_mo_firstn_30sep2009',
 'ohp_all_mo_12m',
 'ohp_std_ever_matchn_30sep2009',
 'ohp_std_ever_inperson',
 'ohp_std_ever_firstn_30sep2009',
 'snap_ever_prenotify07',
 'snap_ever_presurvey12m',
 'snap_ever_matchn_30sep2009',
 'snap_ever_firstn_survey12m',
 'snap_tot_hh_prenotify07',
 'snap_tot_hh_presurvey12m',
 'snap_tot_hh_30sep2009',
 'snap_tot_hh_firstn_survey12m',
 'tanf_ever_prenotify07',
 'tanf_ever_presurvey12m',
 'tanf_ever_matchn_30sep2009',
 'tanf_ever_firstn_survey12m',
 'tanf_tot_hh_prenotify07',
 'tanf_tot_hh_presurvey12m',
 'tanf_tot_hh_30sep2009',
 'tanf_tot_hh_firstn_survey12m',
 'ohp_all_ever_matchn_30sep2009_Enrolled']

In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
tran = le.fit_transform(ed_sample['numhh_list'].tolist())
tran_df = pd.DataFrame(tran, columns=['numhh'])
ed_sample = pd.concat([ed_sample, tran_df], axis=1)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,tanf_ever_prenotify07,tanf_ever_presurvey12m,tanf_ever_matchn_30sep2009,tanf_ever_firstn_survey12m,tanf_tot_hh_prenotify07,tanf_tot_hh_presurvey12m,tanf_tot_hh_30sep2009,tanf_tot_hh_firstn_survey12m,ohp_all_ever_matchn_30sep2009_Enrolled,numhh
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,No,No,No,No,0.0,0.0,0.0,0.0,0,0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,No,No,No,No,0.0,0.0,0.0,0.0,0,1
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,No,No,No,No,0.0,0.0,0.0,0.0,0,0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,No,No,No,No,0.0,0.0,0.0,0.0,1,1
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,No,No,No,No,0.0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,No,No,No,No,0.0,0.0,0.0,0.0,0,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,No,No,No,No,0.0,0.0,0.0,0.0,0,1
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,No,No,No,No,0.0,0.0,0.0,0.0,1,0
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,No,NaN,No,NaN,0.0,NaN,0.0,NaN,0,0
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,No,NaN,No,NaN,0.0,NaN,0.0,NaN,1,0

In [73]:
# Balance check for features.
features = ['treatment_Selected','numhh']
BalanceCheck = sm.OLS(endog = ed_sample['english_list_Requested English materials'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                                       OLS Regression Results
====================================================================================================
Dep. Variable:     english_list_Requested English materials   R-squared:                       0.072
Model:                                                  OLS   Adj. R-squared:                  0.072
Method:                                       Least Squares   F-statistic:                     949.1
Date:                                      Thu, 20 May 2021   Prob (F-statistic):               0.00
Time:                                              06:48:17   Log-Likelihood:                -7617.4
No. Observations:                                     24605   AIC:                         1.524e+04
Df Residuals:                                         24602   BIC:                         1.527e+04
Df Model:                                                 2
Covariance Type:                                  nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.9072      0.003    324.636      0.000       0.902       0.913
treatment_Selected     0.0092      0.004      2.098      0.036       0.001       0.018
numhh                 -0.2258      0.005    -43.112      0.000      -0.236      -0.216
==============================================================================
Omnibus:                     8402.179   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21502.879
Skew:                          -1.934   Prob(JB):                         0.00
Kurtosis:                       5.452   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [74]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['first_day_list_Signed up for lottery list on first day'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                                              OLS Regression Results
==================================================================================================================
Dep. Variable:     first_day_list_Signed up for lottery list on first day   R-squared:                       0.000
Model:                                                                OLS   Adj. R-squared:                  0.000
Method:                                                     Least Squares   F-statistic:                     1.265
Date:                                                    Thu, 20 May 2021   Prob (F-statistic):              0.282
Time:                                                            06:48:44   Log-Likelihood:                -4465.0
No. Observations:                                                   24605   AIC:                             8936.
Df Residuals:                                                       24602   BIC:                             8960.
Df Model:                                                               2
Covariance Type:                                                nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.0909      0.002     36.982      0.000       0.086       0.096
treatment_Selected     0.0061      0.004      1.572      0.116      -0.001       0.014
numhh                 -0.0025      0.005     -0.538      0.591      -0.012       0.007
==============================================================================
Omnibus:                    13436.238   Durbin-Watson:                   2.020
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            67732.221
Skew:                           2.807   Prob(JB):                         0.00
Kurtosis:                       8.879   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [75]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['have_phone_list_Gave Phone Number'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                                    OLS Regression Results
=============================================================================================
Dep. Variable:     have_phone_list_Gave Phone Number   R-squared:                       0.003
Model:                                           OLS   Adj. R-squared:                  0.002
Method:                                Least Squares   F-statistic:                     31.01
Date:                               Thu, 20 May 2021   Prob (F-statistic):           3.53e-14
Time:                                       06:49:11   Log-Likelihood:                -8083.1
No. Observations:                              24605   AIC:                         1.617e+04
Df Residuals:                                  24602   BIC:                         1.620e+04
Df Model:                                          2
Covariance Type:                           nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.8604      0.003    302.100      0.000       0.855       0.866
treatment_Selected     0.0029      0.004      0.650      0.516      -0.006       0.012
numhh                  0.0404      0.005      7.579      0.000       0.030       0.051
==============================================================================
Omnibus:                     9659.126   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            27779.974
Skew:                          -2.189   Prob(JB):                         0.00
Kurtosis:                       5.815   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [79]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['pobox_list_1: POBOX'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     pobox_list_1: POBOX   R-squared:                       0.000
Model:                             OLS   Adj. R-squared:                  0.000
Method:                  Least Squares   F-statistic:                     5.293
Date:                 Thu, 20 May 2021   Prob (F-statistic):            0.00503
Time:                         06:51:06   Log-Likelihood:                 10163.
No. Observations:                24605   AIC:                        -2.032e+04
Df Residuals:                    24602   BIC:                        -2.029e+04
Df Model:                            2
Covariance Type:             nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.0276      0.001     20.334      0.000       0.025       0.030
treatment_Selected     0.0011      0.002      0.534      0.593      -0.003       0.005
numhh                 -0.0083      0.003     -3.252      0.001      -0.013      -0.003
==============================================================================
Omnibus:                    26818.816   Durbin-Watson:                   2.025
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1257675.318
Skew:                           5.912   Prob(JB):                         0.00
Kurtosis:                      35.969   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [48]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['self_list_Signed self up'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     self_list_Signed self up   R-squared:                       0.443
Model:                                  OLS   Adj. R-squared:                  0.443
Method:                       Least Squares   F-statistic:                     9801.
Date:                      Thu, 20 May 2021   Prob (F-statistic):               0.00
Time:                              05:29:46   Log-Likelihood:                 1706.7
No. Observations:                     24605   AIC:                            -3407.
Df Residuals:                         24602   BIC:                            -3383.
Df Model:                                 2
Covariance Type:                  nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.9988      0.002    522.081      0.000       0.995       1.003
treatment_Selected     0.0009      0.003      0.295      0.768      -0.005       0.007
numhh                 -0.4928      0.004   -137.463      0.000      -0.500      -0.486
==============================================================================
Omnibus:                     1210.562   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4554.830
Skew:                          -0.026   Prob(JB):                         0.00
Kurtosis:                       5.107   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [77]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['female_list_1: Female'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     female_list_1: Female   R-squared:                       0.002
Model:                               OLS   Adj. R-squared:                  0.002
Method:                    Least Squares   F-statistic:                     21.32
Date:                   Thu, 20 May 2021   Prob (F-statistic):           5.63e-10
Time:                           06:49:46   Log-Likelihood:                -17729.
No. Observations:                  24605   AIC:                         3.546e+04
Df Residuals:                      24602   BIC:                         3.549e+04
Df Model:                              2
Covariance Type:               nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.5601      0.004    132.886      0.000       0.552       0.568
treatment_Selected    -0.0098      0.007     -1.480      0.139      -0.023       0.003
numhh                 -0.0471      0.008     -5.958      0.000      -0.063      -0.032
==============================================================================
Omnibus:                    86342.404   Durbin-Watson:                   2.012
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4073.869
Skew:                          -0.187   Prob(JB):                         0.00
Kurtosis:                       1.042   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [78]:
# Balance check for features.
BalanceCheck = sm.OLS(endog = ed_sample['birthyear_list'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         birthyear_list   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     2.726
Date:                Thu, 20 May 2021   Prob (F-statistic):             0.0655
Time:                        06:50:05   Log-Likelihood:                -96146.
No. Observations:               24605   AIC:                         1.923e+05
Df Residuals:                   24602   BIC:                         1.923e+05
Df Model:                           2
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const               1968.2800      0.102   1.93e+04      0.000    1968.080    1968.480
treatment_Selected     0.0965      0.160      0.602      0.547      -0.218       0.411
numhh                  0.4015      0.191      2.099      0.036       0.027       0.776
==============================================================================
Omnibus:                    12426.580   Durbin-Watson:                   1.978
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1363.419
Skew:                          -0.116   Prob(JB):                    8.66e-297
Kurtosis:                       1.870   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [17]:
outcome_vars_01_pre_ed = ['any_visit_pre_ed','any_hosp_pre_ed','any_out_pre_ed','any_on_pre_ed','any_off_pre_ed','any_acsc_pre_ed','any_chron_pre_ed','any_inj_pre_ed','any_skin_pre_ed','any_abdo_pre_ed','any_back_pre_ed','any_heart_pre_ed','any_head_pre_ed','any_depres_pre_ed','any_psysub_pre_ed','any_hiun_pre_ed','any_loun_pre_ed',]
outcome_vars_01_ed = ['any_visit_ed','any_hosp_ed', 'any_out_ed', 'any_on_ed', 'any_off_ed',
 'any_acsc_ed',
 'any_chron_ed',
 'any_inj_ed',
 'any_skin_ed', 
 'any_abdo_ed',
 'any_back_ed',
 'any_heart_ed',
 'any_head_ed', 
 'any_depres_ed',
 'any_psysub_ed','any_mail_match_ed','any_inp_match_ed',
 'any_hiun_ed',
 'any_loun_ed']
outcome_vars_val_pre_ed = [
 'num_visit_pre_cens_ed',

 'num_hosp_pre_cens_ed',

 'num_out_pre_cens_ed',

 'num_on_pre_cens_ed',

 'num_off_pre_cens_ed',

 'num_edcnnp_pre_ed',

 'num_edcnpa_pre_ed',

 'num_epct_pre_ed',

 'num_ne_pre_ed',

 'num_unclas_pre_ed',

 'num_acsc_pre_cens_ed',
 'num_chron_pre_cens_ed',

 'num_inj_pre_cens_ed',

 'num_skin_pre_cens_ed',

 'num_abdo_pre_cens_ed',

 'num_back_pre_cens_ed',

 'num_heart_pre_cens_ed',

 'num_head_pre_cens_ed',
 
 'num_depres_pre_cens_ed',

 'num_psysub_pre_cens_ed',


 'charg_tot_pre_ed',

 'ed_charg_tot_pre_ed',

 'num_hiun_pre_cens_ed',

 'num_loun_pre_cens_ed',
]
outcome_vars_val_ed = [ 'num_visit_cens_ed',
 'num_hosp_cens_ed',
 'num_out_cens_ed',
 'num_on_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_ed',
 'num_edcnpa_ed',
 'num_epct_ed',
 'num_ne_ed',
 'num_unclas_ed',
'num_acsc_cens_ed',
 'num_chron_cens_ed',
 'num_inj_cens_ed',
 'num_skin_cens_ed',
 'num_abdo_cens_ed',
 'num_back_cens_ed',
 'num_heart_cens_ed',
'num_head_cens_ed',
 'num_depres_cens_ed',
 'num_mail_match_ed',
 'num_inp_match_ed',
 'charg_tot_ed',
 'ed_charg_tot_ed',
 'num_hiun_cens_ed',
 'num_loun_cens_ed']

In [18]:
ed_sample = pd.get_dummies(ed_sample, columns = ['any_visit_pre_ed',
 'any_visit_ed','any_hosp_pre_ed',
 'any_hosp_ed','any_out_pre_ed',
 'any_out_ed','any_on_pre_ed',
 'any_on_ed', 'any_off_pre_ed',
 'any_off_ed','any_acsc_pre_ed',
 'any_acsc_ed','any_chron_pre_ed',
 'any_chron_ed', 'any_inj_pre_ed',
 'any_inj_ed', 'any_skin_pre_ed',
 'any_skin_ed', 'any_abdo_pre_ed',
 'any_abdo_ed', 'any_back_pre_ed',
 'any_back_ed', 'any_heart_pre_ed',
 'any_heart_ed', 'any_head_pre_ed',
 'any_head_ed', 'any_depres_pre_ed',
 'any_depres_ed', 'any_psysub_pre_ed',
 'any_psysub_ed','any_mail_match_ed','any_inp_match_ed','any_hiun_pre_ed',
 'any_hiun_ed','any_loun_pre_ed',
 'any_loun_ed'], drop_first = True)
ed_sample

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,any_depres_pre_ed_Yes,any_depres_ed_Yes,any_psysub_pre_ed_Yes,any_psysub_ed_Yes,any_mail_match_ed_1.0,any_inp_match_ed_1.0,any_hiun_pre_ed_Yes,any_hiun_ed_Yes,any_loun_pre_ed_Yes,any_loun_ed_Yes
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,0,0,0,0,0,1,0,1,0,0
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0,0,0,0,0,0,1,0,0,0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,0,0,0,0,0,1,1,1,0,0
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0,0,0,0,0,0,0,0,0,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,1,0,1
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,1,0,0,0

In [30]:
columns = list(ed_sample.columns.values)
columns

['person_id',
 'household_id',
 'draw_treat',
 'draw_lottery',
 'applied_app',
 'dt_notify_lottery',
 'dt_retro_coverage',
 'dt_app_decision',
 'postn_death',
 'numhh_list',
 'birthyear_list',
 'last_day_list',
 'week_list',
 'zip_msa_list',
 'sample_ed',
 'num_visit_pre_cens_ed',
 'num_visit_cens_ed',
 'num_hosp_pre_cens_ed',
 'num_hosp_cens_ed',
 'num_out_pre_cens_ed',
 'num_out_cens_ed',
 'num_on_pre_cens_ed',
 'num_on_cens_ed',
 'num_off_pre_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_pre_ed',
 'num_edcnnp_ed',
 'num_edcnpa_pre_ed',
 'num_edcnpa_ed',
 'num_epct_pre_ed',
 'num_epct_ed',
 'num_ne_pre_ed',
 'num_ne_ed',
 'num_unclas_pre_ed',
 'num_unclas_ed',
 'num_acsc_pre_cens_ed',
 'num_acsc_cens_ed',
 'num_chron_pre_cens_ed',
 'num_chron_cens_ed',
 'num_inj_pre_cens_ed',
 'num_inj_cens_ed',
 'num_skin_pre_cens_ed',
 'num_skin_cens_ed',
 'num_abdo_pre_cens_ed',
 'num_abdo_cens_ed',
 'num_back_pre_cens_ed',
 'num_back_cens_ed',
 'num_heart_pre_cens_ed',
 'num_heart_cens_ed',
 'num_head_pre_cens_ed',
 'num_head_cens_ed',
 'num_depres_pre_cens_ed',
 'num_depres_cens_ed',
 'num_psysub_pre_cens_ed',
 'num_psysub_cens_ed',
 'num_mail_match_ed',
 'num_inp_match_ed',
 'charg_tot_pre_ed',
 'charg_tot_ed',
 'ed_charg_tot_pre_ed',
 'ed_charg_tot_ed',
 'num_hiun_pre_cens_ed',
 'num_hiun_cens_ed',
 'num_loun_pre_cens_ed',
 'num_loun_cens_ed',
 'treatment_Selected',
 'english_list_Requested English materials',
 'first_day_list_Signed up for lottery list on first day',
 'have_phone_list_Gave Phone Number',
 'pobox_list_1: POBOX',
 'self_list_Signed self up',
 'female_list_1: Female',
 'approved_app_Yes',
 'ohp_all_ever_firstn_survey0m',
 'ohp_all_ever_firstn_survey6m',
 'ohp_all_ever_inperson',
 'ohp_all_ever_firstn_30sep2009',
 'ohp_all_end_30sep2009',
 'ohp_all_end_survey0m',
 'ohp_all_end_survey6m',
 'ohp_all_end_inperson',
 'ohp_all_at_12m',
 'ohp_all_mo_matchn_30sep2009',
 'ohp_all_mo_firstn_survey0m',
 'ohp_all_mo_firstn_survey6m',
 'ohp_all_mo_inperson',
 'ohp_all_mo_firstn_30sep2009',
 'ohp_all_mo_12m',
 'ohp_std_ever_matchn_30sep2009',
 'ohp_std_ever_inperson',
 'ohp_std_ever_firstn_30sep2009',
 'snap_ever_prenotify07',
 'snap_ever_presurvey12m',
 'snap_ever_matchn_30sep2009',
 'snap_ever_firstn_survey12m',
 'snap_tot_hh_prenotify07',
 'snap_tot_hh_presurvey12m',
 'snap_tot_hh_30sep2009',
 'snap_tot_hh_firstn_survey12m',
 'tanf_ever_prenotify07',
 'tanf_ever_presurvey12m',
 'tanf_ever_matchn_30sep2009',
 'tanf_ever_firstn_survey12m',
 'tanf_tot_hh_prenotify07',
 'tanf_tot_hh_presurvey12m',
 'tanf_tot_hh_30sep2009',
 'tanf_tot_hh_firstn_survey12m',
 'ohp_all_ever_matchn_30sep2009_Enrolled',
 'numhh',
 'any_visit_pre_ed_Yes',
 'any_visit_ed_Yes',
 'any_hosp_pre_ed_Yes',
 'any_hosp_ed_Yes',
 'any_out_pre_ed_Yes',
 'any_out_ed_Yes',
 'any_on_pre_ed_Yes',
 'any_on_ed_Yes',
 'any_off_pre_ed_Yes',
 'any_off_ed_Yes',
 'any_acsc_pre_ed_Yes',
 'any_acsc_ed_Yes',
 'any_chron_pre_ed_Yes',
 'any_chron_ed_Yes',
 'any_inj_pre_ed_Yes',
 'any_inj_ed_Yes',
 'any_skin_pre_ed_Yes',
 'any_skin_ed_Yes',
 'any_abdo_pre_ed_Yes',
 'any_abdo_ed_Yes',
 'any_back_pre_ed_Yes',
 'any_back_ed_Yes',
 'any_heart_pre_ed_Yes',
 'any_heart_ed_Yes',
 'any_head_pre_ed_Yes',
 'any_head_ed_Yes',
 'any_depres_pre_ed_Yes',
 'any_depres_ed_Yes',
 'any_psysub_pre_ed_Yes',
 'any_psysub_ed_Yes',
 'any_mail_match_ed_1.0',
 'any_inp_match_ed_1.0',
 'any_hiun_pre_ed_Yes',
 'any_hiun_ed_Yes',
 'any_loun_pre_ed_Yes',
 'any_loun_ed_Yes']

In [19]:
outcome_vars_01_pre_ed=['any_visit_pre_ed_Yes',
'any_hosp_pre_ed_Yes',
'any_out_pre_ed_Yes',
 'any_on_pre_ed_Yes',
 'any_off_pre_ed_Yes',

'any_acsc_pre_ed_Yes',
 'any_chron_pre_ed_Yes',
 'any_inj_pre_ed_Yes',
 'any_skin_pre_ed_Yes',
 'any_abdo_pre_ed_Yes',
 'any_back_pre_ed_Yes',
 'any_heart_pre_ed_Yes',
 'any_head_pre_ed_Yes',
 'any_depres_pre_ed_Yes',
 'any_psysub_pre_ed_Yes',
 'any_mail_match_ed_1.0',
 'any_hiun_pre_ed_Yes',
 'any_loun_pre_ed_Yes',
 ]

outcome_vars_01_ed=['any_visit_ed_Yes','any_hosp_ed_Yes',

 'any_out_ed_Yes',

 'any_on_ed_Yes',

 'any_off_ed_Yes',
 
 'any_acsc_ed_Yes',

 'any_chron_ed_Yes',

 'any_inj_ed_Yes',

 'any_skin_ed_Yes',

 'any_abdo_ed_Yes',

 'any_back_ed_Yes',

 'any_heart_ed_Yes',

 'any_head_ed_Yes',

 'any_depres_ed_Yes',

 'any_psysub_ed_Yes',

 'any_inp_match_ed_1.0',

 'any_hiun_ed_Yes',

 'any_loun_ed_Yes']

In [57]:
# Balance check for features.
ed_sample['outcome_vars_01_pre_ed']=ed_sample[outcome_vars_01_pre_ed].sum(axis=1)
ed_sample['outcome_vars_01_ed']=ed_sample[outcome_vars_01_ed].sum(axis=1)
ed_sample

<ipython-input-57-1f0f947b193f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ed_sample['outcome_vars_01_pre_ed']=ed_sample[outcome_vars_01_pre_ed].sum(axis=1)
<ipython-input-57-1f0f947b193f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ed_sample['outcome_vars_01_ed']=ed_sample[outcome_vars_01_ed].sum(axis=1)

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,any_psysub_ed_Yes,any_mail_match_ed_1.0,any_inp_match_ed_1.0,any_hiun_pre_ed_Yes,any_hiun_ed_Yes,any_loun_pre_ed_Yes,any_loun_ed_Yes,outcome_vars_01_pre_ed,outcome_vars_01_ed,outcome_vars_val_pre_ed
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0.000000
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,0,0,1,0,1,0,0,0,8,0.000000
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0,0,0,1,0,0,0,5,0,1585.000000
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,0,0,1,1,1,0,0,5,8,3782.399902
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,0,0,0,0,0,1,0,5,0,2731.699951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0.000000
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0,0,0,0,0,0,0,0,0,0.000000
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0.000000
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,1,0,1,0,8,0.000000
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,1,0,0,0,5,0,4869.000000

In [80]:
# Balance check for features.
features = ['treatment_Selected','numhh']
BalanceCheck = sm.OLS(endog = ed_sample['outcome_vars_01_pre_ed'], exog = sm.add_constant(ed_sample[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     outcome_vars_01_pre_ed   R-squared:                       0.017
Model:                                OLS   Adj. R-squared:                  0.017
Method:                     Least Squares   F-statistic:                     209.7
Date:                    Thu, 20 May 2021   Prob (F-statistic):           5.10e-91
Time:                            06:51:50   Log-Likelihood:                -61400.
No. Observations:                   24605   AIC:                         1.228e+05
Df Residuals:                       24602   BIC:                         1.228e+05
Df Model:                               2
Covariance Type:                nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  2.0664      0.025     83.098      0.000       2.018       2.115
treatment_Selected     0.0456      0.039      1.166      0.244      -0.031       0.122
numhh                 -0.9455      0.047    -20.289      0.000      -1.037      -0.854
==============================================================================
Omnibus:                     4113.344   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6510.619
Skew:                           1.240   Prob(JB):                         0.00
Kurtosis:                       3.449   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
outcome_vars_val_pre_ed = [
 'num_visit_pre_cens_ed',

 'num_hosp_pre_cens_ed',

 'num_out_pre_cens_ed',

 'num_on_pre_cens_ed',

 'num_off_pre_cens_ed',

 'num_edcnnp_pre_ed',

 'num_edcnpa_pre_ed',

 'num_epct_pre_ed',

 'num_ne_pre_ed',

 'num_unclas_pre_ed',

 'num_acsc_pre_cens_ed',
 'num_chron_pre_cens_ed',

 'num_inj_pre_cens_ed',

 'num_skin_pre_cens_ed',

 'num_abdo_pre_cens_ed',

 'num_back_pre_cens_ed',

 'num_heart_pre_cens_ed',

 'num_head_pre_cens_ed',
 
 'num_depres_pre_cens_ed',

 'num_psysub_pre_cens_ed',


 'charg_tot_pre_ed',

 'ed_charg_tot_pre_ed',

 'num_hiun_pre_cens_ed',

 'num_loun_pre_cens_ed',
]
outcome_vars_val_ed = [ 'num_visit_cens_ed',
 'num_hosp_cens_ed',
 'num_out_cens_ed',
 'num_on_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_ed',
 'num_edcnpa_ed',
 'num_epct_ed',
 'num_ne_ed',
 'num_unclas_ed',
'num_acsc_cens_ed',
 'num_chron_cens_ed',
 'num_inj_cens_ed',
 'num_skin_cens_ed',
 'num_abdo_cens_ed',
 'num_back_cens_ed',
 'num_heart_cens_ed',
'num_head_cens_ed',
 'num_depres_cens_ed',
 'num_mail_match_ed',
 'num_inp_match_ed',
 'charg_tot_ed',
 'ed_charg_tot_ed',
 'num_hiun_cens_ed',
 'num_loun_cens_ed']

In [42]:
ed_sample=ed_sample.dropna(subset = outcome_vars_val_pre_ed)
ed_sample[outcome_vars_val_pre_ed].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24605 entries, 0 to 24645
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   num_visit_pre_cens_ed   24605 non-null  float32
 1   num_hosp_pre_cens_ed    24605 non-null  float32
 2   num_out_pre_cens_ed     24605 non-null  float32
 3   num_on_pre_cens_ed      24605 non-null  float32
 4   num_off_pre_cens_ed     24605 non-null  float32
 5   num_edcnnp_pre_ed       24605 non-null  float32
 6   num_edcnpa_pre_ed       24605 non-null  float32
 7   num_epct_pre_ed         24605 non-null  float32
 8   num_ne_pre_ed           24605 non-null  float32
 9   num_unclas_pre_ed       24605 non-null  float32
 10  num_acsc_pre_cens_ed    24605 non-null  float32
 11  num_chron_pre_cens_ed   24605 non-null  float32
 12  num_inj_pre_cens_ed     24605 non-null  float32
 13  num_skin_pre_cens_ed    24605 non-null  float32
 14  num_abdo_pre_cens_ed    24605 non-null  float32
 15  num_back_pre_cens_ed    24605 non-null  float32
 16  num_heart_pre_cens_ed   24605 non-null  float32
 17  num_head_pre_cens_ed    24605 non-null  float32
 18  num_depres_pre_cens_ed  24605 non-null  float32
 19  num_psysub_pre_cens_ed  24605 non-null  float32
 20  charg_tot_pre_ed        24605 non-null  float32
 21  ed_charg_tot_pre_ed     24605 non-null  float32
 22  num_hiun_pre_cens_ed    24605 non-null  float32
 23  num_loun_pre_cens_ed    24605 non-null  float32
dtypes: float32(24)
memory usage: 2.4 MB

In [51]:
ed_sample[outcome_vars_val_pre_ed]

,num_visit_pre_cens_ed,num_hosp_pre_cens_ed,num_out_pre_cens_ed,num_on_pre_cens_ed,num_off_pre_cens_ed,num_edcnnp_pre_ed,num_edcnpa_pre_ed,num_epct_pre_ed,num_ne_pre_ed,num_unclas_pre_ed,...,num_abdo_pre_cens_ed,num_back_pre_cens_ed,num_heart_pre_cens_ed,num_head_pre_cens_ed,num_depres_pre_cens_ed,num_psysub_pre_cens_ed,charg_tot_pre_ed,ed_charg_tot_pre_ed,num_hiun_pre_cens_ed,num_loun_pre_cens_ed
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.500000,0.000000,0.500000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,789.500000,789.500000,1.0,0.0
3,1.0,0.0,1.0,0.0,1.0,0.330275,0.000000,0.669725,0.000000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1888.199951,1888.199951,1.0,0.0
4,2.0,0.0,2.0,1.0,1.0,0.000000,0.241379,0.861185,0.897436,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1715.349976,1006.349976,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
24642,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
24643,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
24644,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
24645,1.0,0.0,1.0,1.0,0.0,0.330275,0.000000,0.669725,0.000000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2431.500000,2431.500000,1.0,0.0

In [52]:
ed_sample1 = ed_sample
ed_sample1

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,any_psysub_pre_ed_Yes,any_psysub_ed_Yes,any_mail_match_ed_1.0,any_inp_match_ed_1.0,any_hiun_pre_ed_Yes,any_hiun_ed_Yes,any_loun_pre_ed_Yes,any_loun_ed_Yes,outcome_vars_01_pre_ed,outcome_vars_01_ed
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,0,0,0,1,0,1,0,0,1,7
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0,0,0,0,1,0,0,0,5,0
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,0,0,0,1,1,1,0,0,6,7
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,0,0,0,0,0,0,1,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24641,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
24642,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0,0,0,0,0,0,0,0,0,0
24643,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,0,0,0,0,0,0,0,0,0,0
24644,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,0,1,0,1,1,7
24645,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,1,0,0,0,5,0

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(ed_sample1[outcome_vars_val_pre_ed]))
print(scaler.transform(ed_sample1[outcome_vars_val_pre_ed]))

StandardScaler()
[[-0.4211927  -0.21571547 -0.40554482 ... -0.3487551  -0.3516497
  -0.31164825]
 [-0.4211927  -0.21571547 -0.40554482 ... -0.3487551  -0.3516497
  -0.31164825]
 [ 0.1334472  -0.21571547  0.19719939 ... -0.03542029  0.44860378
  -0.31164825]
 ...
 [-0.4211927  -0.21571547 -0.40554482 ... -0.3487551  -0.3516497
  -0.31164825]
 [-0.4211927  -0.21571547 -0.40554482 ... -0.3487551  -0.3516497
  -0.31164825]
 [ 0.1334472  -0.21571547  0.19719939 ...  0.61625254  0.44860378
  -0.31164825]]

In [81]:
ed_sample1['outcome_vars_val_pre_ed'] = ed_sample1[outcome_vars_val_pre_ed].sum(axis=1)
features = ['treatment_Selected','numhh']
BalanceCheck = sm.OLS(endog = ed_sample1['outcome_vars_val_pre_ed'], exog = sm.add_constant(ed_sample1[features]))
result_BC = BalanceCheck.fit()
print(result_BC.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     outcome_vars_val_pre_ed   R-squared:                       0.004
Model:                                 OLS   Adj. R-squared:                  0.004
Method:                      Least Squares   F-statistic:                     44.30
Date:                     Thu, 20 May 2021   Prob (F-statistic):           6.23e-20
Time:                             06:52:34   Log-Likelihood:            -2.6303e+05
No. Observations:                    24605   AIC:                         5.261e+05
Df Residuals:                        24602   BIC:                         5.261e+05
Df Model:                                2
Covariance Type:                 nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const               3396.1862     90.041     37.718      0.000    3219.700    3572.672
treatment_Selected  -192.5953    141.471     -1.361      0.173    -469.887      84.696
numhh              -1498.3988    168.737     -8.880      0.000   -1829.134   -1167.663
==============================================================================
Omnibus:                    32536.881   Durbin-Watson:                   2.015
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6743798.225
Skew:                           7.571   Prob(JB):                         0.00
Kurtosis:                      82.679   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

<ipython-input-81-8c251962a507>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ed_sample1['outcome_vars_val_pre_ed'] = ed_sample1[outcome_vars_val_pre_ed].sum(axis=1)

In [62]:
# Fit the first-stage OLS and have the weak instrument test.

IV = ['treatment_Selected','numhh']


First_Stage = sm.OLS(endog = ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled'], exog = sm.add_constant(ed_sample[IV]))
res_first_stage = First_Stage.fit()
print(res_first_stage.summary())

                                      OLS Regression Results
==================================================================================================
Dep. Variable:     ohp_all_ever_matchn_30sep2009_Enrolled   R-squared:                       0.077
Model:                                                OLS   Adj. R-squared:                  0.077
Method:                                     Least Squares   F-statistic:                     1026.
Date:                                    Thu, 20 May 2021   Prob (F-statistic):               0.00
Time:                                            06:11:48   Log-Likelihood:                -13005.
No. Observations:                                   24605   AIC:                         2.602e+04
Df Residuals:                                       24602   BIC:                         2.604e+04
Df Model:                                               2
Covariance Type:                                nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.1519      0.003     43.655      0.000       0.145       0.159
treatment_Selected     0.2471      0.005     45.214      0.000       0.236       0.258
numhh                 -0.0394      0.007     -6.040      0.000      -0.052      -0.027
==============================================================================
Omnibus:                     3491.432   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4916.023
Skew:                           1.078   Prob(JB):                         0.00
Kurtosis:                       2.615   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [87]:

# Compte the average outcomes for different sample groups at different time periods.zhey
df_trend_0 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0]
df_trend_1 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==1]

Y_00 = df_trend_0['any_visit_pre_ed_Yes'].mean() # pre-treatment, control group
Y_10 = df_trend_1['any_visit_pre_ed_Yes'].mean() # pre-treatment, treatment group
Y_01 = df_trend_0['any_visit_ed_Yes'].mean() # post-treatment, control group
Y_11 = df_trend_1['any_visit_ed_Yes'].mean() # post-treatment, treatment group


# Compute the trend of each individual subject
df_trend_0['diff'] = df_trend_0['any_visit_ed_Yes'] - df_trend_0['any_visit_pre_ed_Yes'] 
df_trend_1['diff'] = df_trend_1['any_visit_ed_Yes'] - df_trend_1['any_visit_pre_ed_Yes']

<ipython-input-87-11593508c536>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_0['diff'] = df_trend_0['any_visit_ed_Yes'] - df_trend_0['any_visit_pre_ed_Yes']
<ipython-input-87-11593508c536>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_1['diff'] = df_trend_1['any_visit_ed_Yes'] - df_trend_1['any_visit_pre_ed_Yes']

In [89]:

# Compte the average outcomes for different sample groups at different time periods.zhey
df_trend_0 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0]
df_trend_1 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==1]

Y_00 = df_trend_0['any_visit_pre_ed_Yes'].mean() # pre-treatment, control group
Y_10 = df_trend_1['any_visit_pre_ed_Yes'].mean() # pre-treatment, treatment group
Y_01 = df_trend_0['any_visit_ed_Yes'].mean() # post-treatment, control group
Y_11 = df_trend_1['any_visit_ed_Yes'].mean() # post-treatment, treatment group


# Compute the trend of each individual subject
df_trend_0['diff'] = df_trend_0['any_visit_ed_Yes'] - df_trend_0['any_visit_pre_ed_Yes'] 
df_trend_1['diff'] = df_trend_1['any_visit_ed_Yes'] - df_trend_1['any_visit_pre_ed_Yes']

sd0 = df_trend_0['diff'].std()
sd1 = df_trend_1['diff'].std()

n0 = df_trend_0.shape[0]
n1 = df_trend_1.shape[0]


ATT_hat = (Y_11 - Y_10) - (Y_01 - Y_00)

SE_hat = np.sqrt(sd1**2/n1+sd0**2/n0)
t_statistic = ATT_hat/SE_hat

UCB_95 = ATT_hat+1.96*SE_hat
LCB_95 = ATT_hat-1.96*SE_hat

print("The estimated ATT is %0.4f." %ATT_hat)
print("The estimated standard error of ATT is %0.4f." %SE_hat)
print("The t-statistic is:",t_statistic)
print("The 95% confidence interval for ATT is [",LCB_95,",",UCB_95,"].")

The estimated ATT is 0.0783.
The estimated standard error of ATT is 1.2124.
The t-statistic is: 0.06455173526186446
The 95% confidence interval for ATT is [ -2.2980739559067573 , 2.4546012158416235 ].

In [92]:

# Compte the average outcomes for different sample groups at different time periods.zhey
df_trend_0 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0]
df_trend_1 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==1]

Y_00 = df_trend_0['num_visit_pre_cens_ed'].mean() # pre-treatment, control group
Y_10 = df_trend_1['num_visit_pre_cens_ed'].mean() # pre-treatment, treatment group
Y_01 = df_trend_0['num_visit_cens_ed'].mean() # post-treatment, control group
Y_11 = df_trend_1['num_visit_cens_ed'].mean() # post-treatment, treatment group


# Compute the trend of each individual subject
df_trend_0['diff'] = df_trend_0['num_visit_cens_ed'] - df_trend_0['num_visit_pre_cens_ed'] 
df_trend_1['diff'] = df_trend_1['num_visit_cens_ed'] - df_trend_1['num_visit_pre_cens_ed']

sd0 = df_trend_0['diff'].std()
sd1 = df_trend_1['diff'].std()

n0 = df_trend_0.shape[0]
n1 = df_trend_1.shape[0]


ATT_hat = (Y_11 - Y_10) - (Y_01 - Y_00)

SE_hat = np.sqrt(sd1**2/n1+sd0**2/n0)
t_statistic = ATT_hat/SE_hat

UCB_95 = ATT_hat+1.96*SE_hat
LCB_95 = ATT_hat-1.96*SE_hat

print("The estimated ATT is %0.4f." %ATT_hat)
print("The estimated standard error of ATT is %0.4f." %SE_hat)
print("The t-statistic is:",t_statistic)
print("The 95% confidence interval for ATT is [",LCB_95,",",UCB_95,"].")

The estimated ATT is 0.3572.
The estimated standard error of ATT is 0.0347.
The t-statistic is: 10.29653518893485
The 95% confidence interval for ATT is [ 0.28922923915383 , 0.4252304185152374 ].

<ipython-input-92-a49846f92627>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_0['diff'] = df_trend_0['num_visit_cens_ed'] - df_trend_0['num_visit_pre_cens_ed']
<ipython-input-92-a49846f92627>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_1['diff'] = df_trend_1['num_visit_cens_ed'] - df_trend_1['num_visit_pre_cens_ed']

In [102]:
pre = ed_sample.drop(columns = outcome_vars_val_ed + outcome_vars_01_ed)
pre['t'] = 0
post = ed_sample.drop(columns = outcome_vars_val_pre_ed + outcome_vars_01_pre_ed)
post['t'] = 1

name = ['num_visit_cens_ed',
 'num_hosp_cens_ed',
 'num_out_cens_ed',
 'num_on_cens_ed',
 'num_off_cens_ed',
 'num_edcnnp_ed',
 'num_edcnpa_ed',
 'num_epct_ed',
 'num_ne_ed',
 'num_unclas_ed',
'num_acsc_cens_ed',
 'num_chron_cens_ed',
 'num_inj_cens_ed',
 'num_skin_cens_ed',
 'num_abdo_cens_ed',
 'num_back_cens_ed',
 'num_heart_cens_ed',
'num_head_cens_ed',
 'num_depres_cens_ed',
 'num_mail_match_ed',
 'num_inp_match_ed',
 'charg_tot_ed',
 'ed_charg_tot_ed',
 'num_hiun_cens_ed',
 'num_loun_cens_ed']

name1 = ['any_visit_ed_Yes','any_hosp_ed_Yes',

 'any_out_ed_Yes',

 'any_on_ed_Yes',

 'any_off_ed_Yes',
 
 'any_acsc_ed_Yes',

 'any_chron_ed_Yes',

 'any_inj_ed_Yes',

 'any_skin_ed_Yes',

 'any_abdo_ed_Yes',

 'any_back_ed_Yes',

 'any_heart_ed_Yes',

 'any_head_ed_Yes',

 'any_depres_ed_Yes',

 'any_psysub_ed_Yes',

 'any_inp_match_ed_1.0',

 'any_hiun_ed_Yes',

 'any_loun_ed_Yes']

for i in range(24):
    pre[name[i]] = pre[outcome_vars_val_pre_ed[i]]
for j in range(17):
    pre[name1[j]]=pre[outcome_vars_01_pre_ed[j]]
    
df=pd.concat([pre,post],axis=0,ignore_index=True)
df

,person_id,household_id,draw_treat,draw_lottery,applied_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,postn_death,numhh_list,...,any_abdo_ed_Yes,any_back_ed_Yes,any_heart_ed_Yes,any_head_ed_Yes,any_depres_ed_Yes,any_psysub_ed_Yes,any_inp_match_ed_1.0,any_hiun_ed_Yes,num_loun_cens_ed,any_loun_ed_Yes
0,5.0,100005.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,2008-08-12,2008-09-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,NaN,NaN
1,8.0,102094.0,NaN,Lottery Draw 8,NaN,2008-09-11,2008-10-08,NaT,Alive,signed self up + 1 additional person,...,0,0,0,0,0,0,0,0,NaN,NaN
2,9.0,100009.0,NaN,Lottery Draw 1,NaN,2008-03-10,2008-03-11,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,1,NaN,NaN
3,16.0,140688.0,NaN,Lottery Draw 2,NaN,2008-04-07,2008-04-08,NaT,Alive,signed self up + 1 additional person,...,1,0,0,0,0,0,0,1,NaN,NaN
4,18.0,100018.0,NaN,Lottery Draw 4,NaN,2008-05-09,2008-06-09,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49205,74907.0,174907.0,Draw 3: selected in lottery 04/08/2008,Lottery Draw 3,Submitted an Application to OHP,2008-04-16,2008-05-08,2008-07-18,Alive,signed self up,...,0,0,0,0,0,0,0,0,0.0,0.0
49206,74911.0,174911.0,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,2008-08-12,2008-09-08,2008-12-01,Alive,signed self up + 1 additional person,...,0,0,0,0,0,0,0,0,0.0,0.0
49207,74915.0,174915.0,Draw 8: selected in lottery 09/02/2008,Lottery Draw 8,Submitted an Application to OHP,2008-09-11,2008-10-08,2008-11-17,Alive,signed self up,...,0,0,0,0,0,0,0,0,0.0,0.0
49208,74918.0,174918.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,1,1.0,1.0
49209,74920.0,174920.0,NaN,Lottery Draw 6,NaN,2008-07-14,2008-08-08,NaT,Alive,signed self up,...,0,0,0,0,0,0,0,0,0.0,0.0

In [110]:
from linearmodels.iv import IV2SLS
others = ['english_list_Requested English materials',
 'first_day_list_Signed up for lottery list on first day',
 'have_phone_list_Gave Phone Number',
 'pobox_list_1: POBOX',
 'self_list_Signed self up',
 'female_list_1: Female','numhh']
IV_model = IV2SLS(dependent = ed_sample['any_visit_ed_Yes'],endog = ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[others],instruments=ed_sample['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.3746
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3744
No. Observations:               24605   F-statistic:                 1.347e+04
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        08:58:31   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2258     0.0068     33.412     0.0000      0.2126      0.2390
first_day_list_Signed up for lottery list on first day     0.0263     0.0106     2.4872     0.0129      0.0056      0.0470
have_phone_list_Gave Phone Number                          0.0371     0.0078     4.7476     0.0000      0.0218      0.0524
pobox_list_1: POBOX                                       -0.0678     0.0181    -3.7480     0.0002     -0.1032     -0.0323
self_list_Signed self up                                   0.0998     0.0087     11.479     0.0000      0.0828      0.1168
female_list_1: Female                                      0.0111     0.0063     1.7610     0.0782     -0.0013      0.0234
numhh                                                     -0.0336     0.0074    -4.5407     0.0000     -0.0481     -0.0191
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0907     0.0245     3.7055     0.0002      0.0427      0.1387
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False

In [111]:
IV_model = IV2SLS(dependent = ed_sample['num_visit_cens_ed'],endog = ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[others],instruments=ed_sample['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.1754
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1751
No. Observations:               24591   F-statistic:                    4406.1
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        08:58:39   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.7420     0.0259     28.657     0.0000      0.6913      0.7928
first_day_list_Signed up for lottery list on first day     0.0894     0.0542     1.6481     0.0993     -0.0169      0.1956
have_phone_list_Gave Phone Number                          0.0600     0.0381     1.5761     0.1150     -0.0146      0.1347
pobox_list_1: POBOX                                       -0.2567     0.0829    -3.0949     0.0020     -0.4193     -0.0941
self_list_Signed self up                                   0.2671     0.0361     7.3943     0.0000      0.1963      0.3378
female_list_1: Female                                      0.0110     0.0319     0.3443     0.7306     -0.0515      0.0735
numhh                                                     -0.2750     0.0300    -9.1758     0.0000     -0.3337     -0.2162
ohp_all_ever_matchn_30sep2009_Enrolled                     0.3733     0.1229     3.0364     0.0024      0.1323      0.6142
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False

In [114]:
for var in outcome_vars_01_ed:
    IV_model = IV2SLS(dependent = ed_sample[var],endog = ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[others],instruments=ed_sample['treatment_Selected'])
    res_2sls = IV_model.fit()
    print(res_2sls)
    print(var)
    print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][var].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.3746
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3744
No. Observations:               24605   F-statistic:                 1.347e+04
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2258     0.0068     33.412     0.0000      0.2126      0.2390
first_day_list_Signed up for lottery list on first day     0.0263     0.0106     2.4872     0.0129      0.0056      0.0470
have_phone_list_Gave Phone Number                          0.0371     0.0078     4.7476     0.0000      0.0218      0.0524
pobox_list_1: POBOX                                       -0.0678     0.0181    -3.7480     0.0002     -0.1032     -0.0323
self_list_Signed self up                                   0.0998     0.0087     11.479     0.0000      0.0828      0.1168
female_list_1: Female                                      0.0111     0.0063     1.7610     0.0782     -0.0013      0.0234
numhh                                                     -0.0336     0.0074    -4.5407     0.0000     -0.0481     -0.0191
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0907     0.0245     3.7055     0.0002      0.0427      0.1387
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.3016263642199872
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_hosp_ed_Yes   R-squared:                      0.0757
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0754
No. Observations:               24605   F-statistic:                    1861.0
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0538     0.0032     16.634     0.0000      0.0474      0.0601
first_day_list_Signed up for lottery list on first day     0.0088     0.0060     1.4615     0.1439     -0.0030      0.0206
have_phone_list_Gave Phone Number                          0.0003     0.0044     0.0741     0.9410     -0.0083      0.0090
pobox_list_1: POBOX                                       -0.0112     0.0099    -1.1400     0.2543     -0.0305      0.0081
self_list_Signed self up                                   0.0346     0.0045     7.6355     0.0000      0.0257      0.0435
female_list_1: Female                                     -0.0086     0.0035    -2.4513     0.0142     -0.0156     -0.0017
numhh                                                     -0.0108     0.0037    -2.9159     0.0035     -0.0180     -0.0035
ohp_all_ever_matchn_30sep2009_Enrolled                    -0.0075     0.0134    -0.5638     0.5729     -0.0337      0.0187
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_hosp_ed_Yes
0.059704686496897065
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         any_out_ed_Yes   R-squared:                      0.3523
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3521
No. Observations:               24605   F-statistic:                 1.214e+04
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2086     0.0066     31.608     0.0000      0.1956      0.2215
first_day_list_Signed up for lottery list on first day     0.0263     0.0104     2.5190     0.0118      0.0058      0.0467
have_phone_list_Gave Phone Number                          0.0378     0.0077     4.9297     0.0000      0.0228      0.0528
pobox_list_1: POBOX                                       -0.0670     0.0177    -3.7930     0.0001     -0.1016     -0.0324
self_list_Signed self up                                   0.0871     0.0085     10.263     0.0000      0.0705      0.1038
female_list_1: Female                                      0.0129     0.0062     2.0783     0.0377      0.0007      0.0250
numhh                                                     -0.0340     0.0072    -4.6852     0.0000     -0.0482     -0.0198
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1025     0.0241     4.2543     0.0000      0.0553      0.1498
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_out_ed_Yes
0.2801733361866039
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:          any_on_ed_Yes   R-squared:                      0.2834
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2832
No. Observations:               24605   F-statistic:                    8637.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1759     0.0059     30.020     0.0000      0.1644      0.1874
first_day_list_Signed up for lottery list on first day     0.0280     0.0099     2.8283     0.0047      0.0086      0.0474
have_phone_list_Gave Phone Number                          0.0259     0.0071     3.6362     0.0003      0.0119      0.0399
pobox_list_1: POBOX                                       -0.0619     0.0161    -3.8397     0.0001     -0.0935     -0.0303
self_list_Signed self up                                   0.0741     0.0077     9.6830     0.0000      0.0591      0.0891
female_list_1: Female                                      0.0037     0.0058     0.6399     0.5223     -0.0076      0.0150
numhh                                                     -0.0446     0.0065    -6.8628     0.0000     -0.0574     -0.0319
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0647     0.0225     2.8741     0.0041      0.0206      0.1088
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_on_ed_Yes
0.2182751979456452
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         any_off_ed_Yes   R-squared:                      0.2446
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2444
No. Observations:               24605   F-statistic:                    7072.0
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1498     0.0056     26.965     0.0000      0.1389      0.1607
first_day_list_Signed up for lottery list on first day     0.0113     0.0094     1.1981     0.2309     -0.0072      0.0297
have_phone_list_Gave Phone Number                          0.0187     0.0068     2.7377     0.0062      0.0053      0.0321
pobox_list_1: POBOX                                       -0.0362     0.0158    -2.2935     0.0218     -0.0670     -0.0053
self_list_Signed self up                                   0.0599     0.0074     8.0670     0.0000      0.0453      0.0744
female_list_1: Female                                      0.0074     0.0055     1.3391     0.1806     -0.0034      0.0182
numhh                                                     -0.0246     0.0064    -3.8595     0.0001     -0.0371     -0.0121
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0771     0.0216     3.5775     0.0003      0.0349      0.1194
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_off_ed_Yes
0.18938583351166274
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_acsc_ed_Yes   R-squared:                      0.0574
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0571
No. Observations:               24605   F-statistic:                    1172.8
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0324     0.0026     12.294     0.0000      0.0272      0.0376
first_day_list_Signed up for lottery list on first day     0.0005     0.0048     0.0936     0.9255     -0.0090      0.0099
have_phone_list_Gave Phone Number                          0.0047     0.0033     1.4220     0.1550     -0.0018      0.0111
pobox_list_1: POBOX                                       -0.0151     0.0072    -2.0946     0.0362     -0.0293     -0.0010
self_list_Signed self up                                  -0.0018     0.0035    -0.5068     0.6123     -0.0087      0.0051
female_list_1: Female                                      0.0247     0.0028     8.9327     0.0000      0.0192      0.0301
numhh                                                     -0.0137     0.0030    -4.5063     0.0000     -0.0196     -0.0077
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0197     0.0111     1.7802     0.0750     -0.0020      0.0414
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_acsc_ed_Yes

0.036272202011555746
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_chron_ed_Yes   R-squared:                      0.1155
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1152
No. Observations:               24605   F-statistic:                    2713.3
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0779     0.0035     22.092     0.0000      0.0709      0.0848
first_day_list_Signed up for lottery list on first day     0.0121     0.0070     1.7258     0.0844     -0.0016      0.0258
have_phone_list_Gave Phone Number                          0.0047     0.0049     0.9534     0.3404     -0.0050      0.0144
pobox_list_1: POBOX                                       -0.0280     0.0107    -2.6058     0.0092     -0.0490     -0.0069
self_list_Signed self up                                   0.0269     0.0050     5.3689     0.0000      0.0171      0.0368
female_list_1: Female                                      0.0004     0.0040     0.1049     0.9165     -0.0074      0.0083
numhh                                                     -0.0230     0.0044    -5.2803     0.0000     -0.0316     -0.0145
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0271     0.0156     1.7318     0.0833     -0.0036      0.0577
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_chron_ed_Yes
0.08137170982238391
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         any_inj_ed_Yes   R-squared:                      0.1647
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1644
No. Observations:               24605   F-statistic:                    4205.4
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1107     0.0045     24.402     0.0000      0.1018      0.1196
first_day_list_Signed up for lottery list on first day     0.0175     0.0082     2.1267     0.0334      0.0014      0.0336
have_phone_list_Gave Phone Number                          0.0132     0.0058     2.2651     0.0235      0.0018      0.0246
pobox_list_1: POBOX                                       -0.0227     0.0135    -1.6783     0.0933     -0.0492      0.0038
self_list_Signed self up                                   0.0442     0.0061     7.1937     0.0000      0.0321      0.0562
female_list_1: Female                                     -0.0240     0.0047    -5.0671     0.0000     -0.0333     -0.0147
numhh                                                     -0.0273     0.0052    -5.2947     0.0000     -0.0375     -0.0172
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0556     0.0184     3.0149     0.0026      0.0194      0.0917
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_inj_ed_Yes
0.1268992082174192
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_skin_ed_Yes   R-squared:                      0.0405
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0402
No. Observations:               24605   F-statistic:                    888.50
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0314     0.0020     15.826     0.0000      0.0275      0.0353
first_day_list_Signed up for lottery list on first day    -0.0006     0.0042    -0.1525     0.8788     -0.0089      0.0076
have_phone_list_Gave Phone Number                          0.0013     0.0031     0.4270     0.6694     -0.0047      0.0073
pobox_list_1: POBOX                                       -0.0089     0.0067    -1.3193     0.1871     -0.0221      0.0043
self_list_Signed self up                                   0.0125     0.0030     4.1446     0.0000      0.0066      0.0185
female_list_1: Female                                     -0.0070     0.0025    -2.7801     0.0054     -0.0119     -0.0021
numhh                                                     -0.0074     0.0026    -2.8726     0.0041     -0.0124     -0.0023
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0035     0.0096     0.3626     0.7169     -0.0153      0.0223
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_skin_ed_Yes
0.03167130323132891
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_abdo_ed_Yes   R-squared:                      0.0358
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0355
No. Observations:               24605   F-statistic:                    814.31
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0141     0.0024     5.7443     0.0000      0.0093      0.0189
first_day_list_Signed up for lottery list on first day     0.0130     0.0046     2.8396     0.0045      0.0040      0.0219
have_phone_list_Gave Phone Number                          0.0003     0.0029     0.0951     0.9243     -0.0054      0.0060
pobox_list_1: POBOX                                       -0.0083     0.0064    -1.2932     0.1959     -0.0208      0.0043
self_list_Signed self up                                   0.0125     0.0032     3.8703     0.0001      0.0061      0.0188
female_list_1: Female                                      0.0165     0.0023     7.0907     0.0000      0.0119      0.0210
numhh                                                     -0.0025     0.0028    -0.8652     0.3869     -0.0080      0.0031
ohp_all_ever_matchn_30sep2009_Enrolled                    -0.0028     0.0092    -0.3019     0.7627     -0.0209      0.0153
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_abdo_ed_Yes
0.025946929167558315
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_back_ed_Yes   R-squared:                      0.0331
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0327
No. Observations:               24605   F-statistic:                    715.42
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0215     0.0020     10.979     0.0000      0.0177      0.0254
first_day_list_Signed up for lottery list on first day     0.0013     0.0039     0.3383     0.7351     -0.0063      0.0089
have_phone_list_Gave Phone Number                          0.0052     0.0027     1.9454     0.0517  -3.874e-05      0.0104
pobox_list_1: POBOX                                       -0.0062     0.0062    -0.9975     0.3185     -0.0183      0.0060
self_list_Signed self up                                   0.0062     0.0027     2.3048     0.0212      0.0009      0.0116
female_list_1: Female                                      0.0012     0.0022     0.5184     0.6042     -0.0032      0.0055
numhh                                                     -0.0114     0.0022    -5.1231     0.0000     -0.0158     -0.0070
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0049     0.0087     0.5657     0.5716     -0.0122      0.0221
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_back_ed_Yes
0.024074470361652042
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_heart_ed_Yes   R-squared:                      0.0276
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0273
No. Observations:               24605   F-statistic:                    639.36
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0142     0.0021     6.7230     0.0000      0.0100      0.0183
first_day_list_Signed up for lottery list on first day     0.0068     0.0039     1.7365     0.0825     -0.0009      0.0145
have_phone_list_Gave Phone Number                          0.0042     0.0026     1.6060     0.1083     -0.0009      0.0093
pobox_list_1: POBOX                                       -0.0056     0.0058    -0.9659     0.3341     -0.0171      0.0058
self_list_Signed self up                                   0.0095     0.0028     3.3539     0.0008      0.0039      0.0150
female_list_1: Female                                      0.0003     0.0022     0.1211     0.9036     -0.0040      0.0045
numhh                                                     -0.0005     0.0025    -0.1821     0.8555     -0.0054      0.0045
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0026     0.0084     0.3112     0.7557     -0.0139      0.0192
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_heart_ed_Yes
0.022362508024823455

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_head_ed_Yes   R-squared:                      0.0277
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0274
No. Observations:               24605   F-statistic:                    482.85
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:52   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0094     0.0020     4.8287     0.0000      0.0056      0.0133
first_day_list_Signed up for lottery list on first day    -0.0016     0.0031    -0.5256     0.5992     -0.0077      0.0045
have_phone_list_Gave Phone Number                         -0.0019     0.0023    -0.8272     0.4081     -0.0064      0.0026
pobox_list_1: POBOX                                       -0.0064     0.0047    -1.3634     0.1727     -0.0156      0.0028
self_list_Signed self up                                   0.0027     0.0025     1.1066     0.2685     -0.0021      0.0076
female_list_1: Female                                      0.0135     0.0018     7.5641     0.0000      0.0100      0.0170
numhh                                                     -0.0021     0.0022    -0.9405     0.3470     -0.0063      0.0022
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0163     0.0074     2.1911     0.0284      0.0017      0.0308
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_head_ed_Yes
0.013535202225551038
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      any_depres_ed_Yes   R-squared:                      0.0199
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0196
No. Observations:               24605   F-statistic:                    403.54
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:53   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0139     0.0014     9.6577     0.0000      0.0111      0.0167
first_day_list_Signed up for lottery list on first day     0.0030     0.0031     0.9605     0.3368     -0.0031      0.0090
have_phone_list_Gave Phone Number                         -0.0004     0.0022    -0.1641     0.8696     -0.0047      0.0040
pobox_list_1: POBOX                                       -0.0053     0.0044    -1.1984     0.2308     -0.0140      0.0034
self_list_Signed self up                                   0.0063     0.0020     3.1552     0.0016      0.0024      0.0102
female_list_1: Female                                     -0.0019     0.0017    -1.0907     0.2754     -0.0053      0.0015
numhh                                                     -0.0072     0.0015    -4.7191     0.0000     -0.0102     -0.0042
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0041     0.0066     0.6114     0.5410     -0.0090      0.0171
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_depres_ed_Yes
0.013321206933447464
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      any_psysub_ed_Yes   R-squared:                      0.0475
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0472
No. Observations:               24605   F-statistic:                    995.70
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:53   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0344     0.0021     16.755     0.0000      0.0304      0.0385
first_day_list_Signed up for lottery list on first day     0.0084     0.0047     1.7838     0.0745     -0.0008      0.0177
have_phone_list_Gave Phone Number                         -0.0025     0.0034    -0.7548     0.4504     -0.0092      0.0041
pobox_list_1: POBOX                                       -0.0194     0.0061    -3.2071     0.0013     -0.0313     -0.0076
self_list_Signed self up                                   0.0180     0.0031     5.8105     0.0000      0.0119      0.0241
female_list_1: Female                                     -0.0097     0.0027    -3.6481     0.0003     -0.0149     -0.0045
numhh                                                     -0.0112     0.0026    -4.2583     0.0000     -0.0164     -0.0060
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0081     0.0101     0.7982     0.4248     -0.0118      0.0280
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_psysub_ed_Yes
0.032794778514872676
                           IV-2SLS Estimation Summary
================================================================================
Dep. Variable:     any_inp_match_ed_1.0   R-squared:                      0.0764
Estimator:                      IV-2SLS   Adj. R-squared:                 0.0761
No. Observations:                 24605   F-statistic:                    3034.9
Date:                  Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                          09:12:53   Distribution:                  chi2(8)
Cov. Estimator:                  robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0866     0.0043     20.037     0.0000      0.0781      0.0950
first_day_list_Signed up for lottery list on first day    -0.0118     0.0074    -1.5934     0.1111     -0.0264      0.0027
have_phone_list_Gave Phone Number                          0.0029     0.0052     0.5631     0.5734     -0.0073      0.0132
pobox_list_1: POBOX                                       -0.0322     0.0115    -2.7889     0.0053     -0.0548     -0.0096
self_list_Signed self up                                  -0.0179     0.0060    -2.9751     0.0029     -0.0296     -0.0061
female_list_1: Female                                     -0.0129     0.0044    -2.9195     0.0035     -0.0215     -0.0042
numhh                                                     -0.0288     0.0053    -5.3922     0.0000     -0.0392     -0.0183
ohp_all_ever_matchn_30sep2009_Enrolled                     0.2827     0.0183     15.455     0.0000      0.2469      0.3186
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_inp_match_ed_1.0
0.0921249732505885
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_hiun_ed_Yes   R-squared:                      0.2602
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2599
No. Observations:               24605   F-statistic:                    7617.0
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:53   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1555     0.0057     27.362     0.0000      0.1444      0.1667
first_day_list_Signed up for lottery list on first day     0.0052     0.0095     0.5508     0.5818     -0.0133      0.0238
have_phone_list_Gave Phone Number                          0.0169     0.0069     2.4415     0.0146      0.0033      0.0306
pobox_list_1: POBOX                                       -0.0304     0.0163    -1.8658     0.0621     -0.0623      0.0015
self_list_Signed self up                                   0.0760     0.0075     10.166     0.0000      0.0613      0.0906
female_list_1: Female                                      0.0026     0.0056     0.4564     0.6481     -0.0084      0.0136
numhh                                                     -0.0403     0.0063    -6.3561     0.0000     -0.0527     -0.0279
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0759     0.0220     3.4535     0.0006      0.0328      0.1189
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_hiun_ed_Yes
0.19805264284185747
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        any_loun_ed_Yes   R-squared:                      0.1981
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1979
No. Observations:               24605   F-statistic:                    5490.1
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:12:53   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1288     0.0052     24.951     0.0000      0.1187      0.1389
first_day_list_Signed up for lottery list on first day     0.0249     0.0090     2.7781     0.0055      0.0073      0.0425
have_phone_list_Gave Phone Number                          0.0130     0.0065     2.0195     0.0434      0.0004      0.0257
pobox_list_1: POBOX                                       -0.0587     0.0136    -4.3199     0.0000     -0.0854     -0.0321
self_list_Signed self up                                   0.0502     0.0068     7.3585     0.0000      0.0368      0.0636
female_list_1: Female                                      0.0074     0.0052     1.4253     0.1541     -0.0028      0.0176
numhh                                                     -0.0169     0.0059    -2.8715     0.0041     -0.0284     -0.0054
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0409     0.0201     2.0339     0.0420      0.0015      0.0802
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_loun_ed_Yes
0.16172694200727583

In [115]:
for var in outcome_vars_val_ed:
    IV_model = IV2SLS(dependent = ed_sample[var],endog = ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[others],instruments=ed_sample['treatment_Selected'])
    res_2sls = IV_model.fit()
    print(res_2sls)
    print(var)
    print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][var].mean())

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.1754
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1751
No. Observations:               24591   F-statistic:                    4406.1
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:02   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.7420     0.0259     28.657     0.0000      0.6913      0.7928
first_day_list_Signed up for lottery list on first day     0.0894     0.0542     1.6481     0.0993     -0.0169      0.1956
have_phone_list_Gave Phone Number                          0.0600     0.0381     1.5761     0.1150     -0.0146      0.1347
pobox_list_1: POBOX                                       -0.2567     0.0829    -3.0949     0.0020     -0.4193     -0.0941
self_list_Signed self up                                   0.2671     0.0361     7.3943     0.0000      0.1963      0.3378
female_list_1: Female                                      0.0110     0.0319     0.3443     0.7306     -0.0515      0.0735
numhh                                                     -0.2750     0.0300    -9.1758     0.0000     -0.3337     -0.2162
ohp_all_ever_matchn_30sep2009_Enrolled                     0.3733     0.1229     3.0364     0.0024      0.1323      0.6142
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_visit_cens_ed
0.8093963861465454
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_hosp_cens_ed   R-squared:                      0.0484
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0481
No. Observations:               24605   F-statistic:                    1184.2
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:02   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0851     0.0061     13.861     0.0000      0.0731      0.0972
first_day_list_Signed up for lottery list on first day     0.0092     0.0114     0.8074     0.4194     -0.0131      0.0314
have_phone_list_Gave Phone Number                          0.0061     0.0087     0.7089     0.4784     -0.0108      0.0231
pobox_list_1: POBOX                                       -0.0355     0.0152    -2.3347     0.0196     -0.0653     -0.0057
self_list_Signed self up                                   0.0568     0.0086     6.6428     0.0000      0.0401      0.0736
female_list_1: Female                                     -0.0165     0.0070    -2.3673     0.0179     -0.0302     -0.0028
numhh                                                     -0.0303     0.0063    -4.8068     0.0000     -0.0427     -0.0180
ohp_all_ever_matchn_30sep2009_Enrolled                    -0.0178     0.0269    -0.6619     0.5081     -0.0704      0.0349
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_hosp_cens_ed
0.08912903815507889
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        num_out_cens_ed   R-squared:                      0.1673
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1670
No. Observations:               24591   F-statistic:                    4123.0
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:02   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.6583     0.0233     28.269     0.0000      0.6127      0.7040
first_day_list_Signed up for lottery list on first day     0.0784     0.0499     1.5702     0.1164     -0.0195      0.1762
have_phone_list_Gave Phone Number                          0.0554     0.0347     1.5974     0.1102     -0.0126      0.1233
pobox_list_1: POBOX                                       -0.2246     0.0772    -2.9111     0.0036     -0.3758     -0.0734
self_list_Signed self up                                   0.2086     0.0329     6.3398     0.0000      0.1441      0.2730
female_list_1: Female                                      0.0282     0.0291     0.9697     0.3322     -0.0288      0.0853
numhh                                                     -0.2473     0.0278    -8.9026     0.0000     -0.3017     -0.1928
ohp_all_ever_matchn_30sep2009_Enrolled                     0.3954     0.1127     3.5072     0.0005      0.1744      0.6164
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_out_cens_ed
0.7212114930152893
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:         num_on_cens_ed   R-squared:                      0.1534
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1531
No. Observations:               24594   F-statistic:                    3707.3
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.4190     0.0159     26.313     0.0000      0.3878      0.4502
first_day_list_Signed up for lottery list on first day     0.0715     0.0340     2.1047     0.0353      0.0049      0.1381
have_phone_list_Gave Phone Number                          0.0314     0.0233     1.3508     0.1768     -0.0142      0.0770
pobox_list_1: POBOX                                       -0.1702     0.0492    -3.4613     0.0005     -0.2666     -0.0738
self_list_Signed self up                                   0.1536     0.0221     6.9450     0.0000      0.1102      0.1969
female_list_1: Female                                      0.0103     0.0193     0.5330     0.5941     -0.0275      0.0481
numhh                                                     -0.1585     0.0187    -8.4697     0.0000     -0.1952     -0.1219
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1863     0.0749     2.4869     0.0129      0.0395      0.3332
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_on_cens_ed
0.45213761925697327

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        num_off_cens_ed   R-squared:                      0.1319
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1316
No. Observations:               24599   F-statistic:                    3186.3
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.3294     0.0134     24.586     0.0000      0.3032      0.3557
first_day_list_Signed up for lottery list on first day     0.0270     0.0288     0.9361     0.3492     -0.0295      0.0835
have_phone_list_Gave Phone Number                          0.0355     0.0199     1.7881     0.0738     -0.0034      0.0745
pobox_list_1: POBOX                                       -0.0904     0.0454    -1.9903     0.0466     -0.1793     -0.0014
self_list_Signed self up                                   0.1113     0.0190     5.8434     0.0000      0.0740      0.1486
female_list_1: Female                                     -0.0051     0.0169    -0.2989     0.7650     -0.0382      0.0281
numhh                                                     -0.1308     0.0158    -8.2939     0.0000     -0.1617     -0.0999
ohp_all_ever_matchn_30sep2009_Enrolled                     0.2141     0.0663     3.2291     0.0012      0.0841      0.3440
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_off_cens_ed
0.36313536763191223
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:          num_edcnnp_ed   R-squared:                      0.1038
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1035
No. Observations:               24597   F-statistic:                    2532.4
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1486     0.0069     21.452     0.0000      0.1350      0.1622
first_day_list_Signed up for lottery list on first day     0.0433     0.0156     2.7667     0.0057      0.0126      0.0739
have_phone_list_Gave Phone Number                          0.0205     0.0104     1.9756     0.0482      0.0002      0.0408
pobox_list_1: POBOX                                       -0.0519     0.0207    -2.5006     0.0124     -0.0925     -0.0112
self_list_Signed self up                                   0.0722     0.0095     7.5951     0.0000      0.0535      0.0908
female_list_1: Female                                     -0.0254     0.0091    -2.8078     0.0050     -0.0432     -0.0077
numhh                                                     -0.0490     0.0080    -6.1277     0.0000     -0.0646     -0.0333
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0527     0.0346     1.5228     0.1278     -0.0151      0.1205
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_edcnnp_ed
0.1721857339143753

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:          num_edcnpa_ed   R-squared:                      0.0560
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0557
No. Observations:               24603   F-statistic:                    1219.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0583     0.0036     16.238     0.0000      0.0512      0.0653
first_day_list_Signed up for lottery list on first day    -0.0007     0.0073    -0.0900     0.9283     -0.0149      0.0136
have_phone_list_Gave Phone Number                          0.0011     0.0052     0.2028     0.8393     -0.0092      0.0113
pobox_list_1: POBOX                                       -0.0335     0.0082    -4.0652     0.0000     -0.0496     -0.0173
self_list_Signed self up                                   0.0097     0.0049     1.9874     0.0469      0.0001      0.0193
female_list_1: Female                                      0.0170     0.0044     3.8914     0.0001      0.0084      0.0255
numhh                                                     -0.0233     0.0043    -5.4117     0.0000     -0.0317     -0.0149
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0348     0.0180     1.9366     0.0528     -0.0004      0.0701
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_edcnpa_ed
0.05918457359075546
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:            num_epct_ed   R-squared:                      0.1419
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1417
No. Observations:               24592   F-statistic:                    3355.2
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2524     0.0102     24.811     0.0000      0.2325      0.2724
first_day_list_Signed up for lottery list on first day     0.0211     0.0213     0.9898     0.3223     -0.0207      0.0629
have_phone_list_Gave Phone Number                          0.0211     0.0150     1.4098     0.1586     -0.0082      0.0505
pobox_list_1: POBOX                                       -0.0895     0.0310    -2.8863     0.0039     -0.1503     -0.0287
self_list_Signed self up                                   0.0858     0.0143     6.0034     0.0000      0.0578      0.1138
female_list_1: Female                                      0.0017     0.0125     0.1378     0.8904     -0.0228      0.0263
numhh                                                     -0.0944     0.0125    -7.5737     0.0000     -0.1188     -0.0700
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1852     0.0491     3.7701     0.0002      0.0889      0.2815
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_epct_ed
0.2821658253669739

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:              num_ne_ed   R-squared:                      0.0981
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0978
No. Observations:               24597   F-statistic:                    2170.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1417     0.0074     19.151     0.0000      0.1272      0.1562
first_day_list_Signed up for lottery list on first day     0.0064     0.0154     0.4128     0.6798     -0.0239      0.0366
have_phone_list_Gave Phone Number                          0.0218     0.0101     2.1571     0.0310      0.0020      0.0416
pobox_list_1: POBOX                                       -0.0432     0.0259    -1.6655     0.0958     -0.0939      0.0076
self_list_Signed self up                                   0.0290     0.0104     2.7989     0.0051      0.0087      0.0494
female_list_1: Female                                      0.0385     0.0090     4.2902     0.0000      0.0209      0.0561
numhh                                                     -0.0680     0.0088    -7.7435     0.0000     -0.0852     -0.0508
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0935     0.0349     2.6776     0.0074      0.0251      0.1619
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_ne_ed
0.1581902801990509
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:          num_unclas_ed   R-squared:                      0.0797
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0794
No. Observations:               24602   F-statistic:                    1761.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:03   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1549     0.0073     21.201     0.0000      0.1406      0.1692
first_day_list_Signed up for lottery list on first day     0.0169     0.0167     1.0094     0.3128     -0.0159      0.0497
have_phone_list_Gave Phone Number                          0.0095     0.0116     0.8267     0.4084     -0.0131      0.0322
pobox_list_1: POBOX                                       -0.0454     0.0291    -1.5627     0.1181     -0.1024      0.0115
self_list_Signed self up                                   0.0637     0.0110     5.7666     0.0000      0.0420      0.0853
female_list_1: Female                                     -0.0274     0.0093    -2.9405     0.0033     -0.0457     -0.0091
numhh                                                     -0.0676     0.0088    -7.6795     0.0000     -0.0849     -0.0504
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0574     0.0374     1.5348     0.1248     -0.0159      0.1307
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_unclas_ed
0.14691562950611115

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_acsc_cens_ed   R-squared:                      0.0410
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0407
No. Observations:               24604   F-statistic:                    811.04
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0456     0.0041     11.159     0.0000      0.0376      0.0536
first_day_list_Signed up for lottery list on first day    -0.0041     0.0075    -0.5395     0.5895     -0.0188      0.0107
have_phone_list_Gave Phone Number                          0.0075     0.0056     1.3483     0.1776     -0.0034      0.0184
pobox_list_1: POBOX                                       -0.0201     0.0137    -1.4667     0.1425     -0.0470      0.0068
self_list_Signed self up                                  -0.0014     0.0053    -0.2605     0.7945     -0.0119      0.0091
female_list_1: Female                                      0.0337     0.0046     7.2935     0.0000      0.0247      0.0428
numhh                                                     -0.0256     0.0047    -5.4792     0.0000     -0.0348     -0.0164
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0301     0.0190     1.5880     0.1123     -0.0071      0.0673
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_acsc_cens_ed
0.05002407729625702
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_chron_cens_ed   R-squared:                      0.0657
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0654
No. Observations:               24603   F-statistic:                    1453.4
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1510     0.0084     17.976     0.0000      0.1345      0.1675
first_day_list_Signed up for lottery list on first day     0.0149     0.0177     0.8409     0.4004     -0.0199      0.0497
have_phone_list_Gave Phone Number                          0.0069     0.0129     0.5357     0.5922     -0.0184      0.0323
pobox_list_1: POBOX                                       -0.0799     0.0222    -3.5937     0.0003     -0.1234     -0.0363
self_list_Signed self up                                   0.0617     0.0117     5.2545     0.0000      0.0387      0.0847
female_list_1: Female                                     -0.0091     0.0105    -0.8731     0.3826     -0.0296      0.0114
numhh                                                     -0.0619     0.0095    -6.4952     0.0000     -0.0806     -0.0433
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0462     0.0410     1.1279     0.2594     -0.0341      0.1265
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_chron_cens_ed
0.14760325849056244

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        num_inj_cens_ed   R-squared:                      0.1313
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1310
No. Observations:               24599   F-statistic:                    3054.2
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2502     0.0098     25.596     0.0000      0.2310      0.2694
first_day_list_Signed up for lottery list on first day     0.0248     0.0203     1.2191     0.2228     -0.0151      0.0647
have_phone_list_Gave Phone Number                          0.0279     0.0146     1.9108     0.0560     -0.0007      0.0565
pobox_list_1: POBOX                                       -0.0398     0.0339    -1.1737     0.2405     -0.1063      0.0267
self_list_Signed self up                                   0.0936     0.0139     6.7442     0.0000      0.0664      0.1208
female_list_1: Female                                     -0.0709     0.0123    -5.7408     0.0000     -0.0951     -0.0467
numhh                                                     -0.0882     0.0119    -7.4301     0.0000     -0.1115     -0.0650
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1884     0.0481     3.9156     0.0001      0.0941      0.2827
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_inj_cens_ed
0.2693954110145569
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_skin_cens_ed   R-squared:                      0.0292
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0289
No. Observations:               24604   F-statistic:                    615.00
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0514     0.0038     13.448     0.0000      0.0439      0.0589
first_day_list_Signed up for lottery list on first day    -0.0060     0.0073    -0.8232     0.4104     -0.0202      0.0083
have_phone_list_Gave Phone Number                         -0.0025     0.0060    -0.4086     0.6828     -0.0142      0.0093
pobox_list_1: POBOX                                       -0.0170     0.0113    -1.5013     0.1333     -0.0392      0.0052
self_list_Signed self up                                   0.0191     0.0057     3.3454     0.0008      0.0079      0.0303
female_list_1: Female                                     -0.0128     0.0049    -2.6090     0.0091     -0.0224     -0.0032
numhh                                                     -0.0106     0.0050    -2.1136     0.0345     -0.0204     -0.0008
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0242     0.0189     1.2833     0.1994     -0.0128      0.0613
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_skin_cens_ed
0.04911454766988754

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_abdo_cens_ed   R-squared:                      0.0257
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0253
No. Observations:               24605   F-statistic:                    587.22
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0202     0.0038     5.3773     0.0000      0.0129      0.0276
first_day_list_Signed up for lottery list on first day     0.0160     0.0073     2.2035     0.0276      0.0018      0.0302
have_phone_list_Gave Phone Number                          0.0015     0.0048     0.3059     0.7597     -0.0079      0.0108
pobox_list_1: POBOX                                       -0.0066     0.0121    -0.5457     0.5853     -0.0304      0.0171
self_list_Signed self up                                   0.0171     0.0049     3.5046     0.0005      0.0075      0.0266
female_list_1: Female                                      0.0237     0.0038     6.2386     0.0000      0.0163      0.0312
numhh                                                     -0.0087     0.0042    -2.0431     0.0410     -0.0170     -0.0004
ohp_all_ever_matchn_30sep2009_Enrolled                    -0.0061     0.0150    -0.4050     0.6855     -0.0356      0.0234
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_abdo_cens_ed
0.035469718277454376
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_back_cens_ed   R-squared:                      0.0238
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0235
No. Observations:               24603   F-statistic:                    510.45
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0353     0.0032     10.888     0.0000      0.0290      0.0417
first_day_list_Signed up for lottery list on first day     0.0022     0.0067     0.3234     0.7464     -0.0109      0.0152
have_phone_list_Gave Phone Number                          0.0106     0.0044     2.3975     0.0165      0.0019      0.0193
pobox_list_1: POBOX                                       -0.0131     0.0090    -1.4570     0.1451     -0.0308      0.0045
self_list_Signed self up                                   0.0067     0.0050     1.3319     0.1829     -0.0032      0.0166
female_list_1: Female                                     -0.0058     0.0039    -1.4856     0.1374     -0.0135      0.0019
numhh                                                     -0.0161     0.0037    -4.3940     0.0000     -0.0233     -0.0089
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0086     0.0153     0.5613     0.5746     -0.0214      0.0386
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_back_cens_ed
0.03402525186538696

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_heart_cens_ed   R-squared:                      0.0226
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0223
No. Observations:               24603   F-statistic:                    501.59
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0169     0.0026     6.5683     0.0000      0.0119      0.0220
first_day_list_Signed up for lottery list on first day     0.0117     0.0061     1.9108     0.0560     -0.0003      0.0237
have_phone_list_Gave Phone Number                          0.0080     0.0033     2.4427     0.0146      0.0016      0.0144
pobox_list_1: POBOX                                       -0.0049     0.0092    -0.5300     0.5961     -0.0230      0.0132
self_list_Signed self up                                   0.0117     0.0035     3.3338     0.0009      0.0048      0.0186
female_list_1: Female                                     -0.0034     0.0029    -1.1484     0.2508     -0.0091      0.0024
numhh                                                     -0.0042     0.0033    -1.2799     0.2006     -0.0107      0.0023
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0073     0.0119     0.6097     0.5420     -0.0161      0.0307
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_heart_cens_ed
0.02776588872075081
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_head_cens_ed   R-squared:                      0.0182
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0179
No. Observations:               24605   F-statistic:                    327.88
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0134     0.0032     4.1608     0.0000      0.0071      0.0197
first_day_list_Signed up for lottery list on first day    -0.0061     0.0045    -1.3679     0.1713     -0.0149      0.0026
have_phone_list_Gave Phone Number                         -0.0024     0.0040    -0.6140     0.5392     -0.0103      0.0054
pobox_list_1: POBOX                                       -0.0045     0.0103    -0.4377     0.6616     -0.0247      0.0157
self_list_Signed self up                                   0.0058     0.0039     1.5058     0.1321     -0.0018      0.0134
female_list_1: Female                                      0.0195     0.0031     6.2176     0.0000      0.0133      0.0256
numhh                                                     -0.0046     0.0035    -1.3053     0.1918     -0.0115      0.0023
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0177     0.0126     1.4032     0.1606     -0.0070      0.0424
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_head_cens_ed
0.019955061376094818
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:     num_depres_cens_ed   R-squared:                      0.0113
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0110
No. Observations:               24605   F-statistic:                    282.34
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:04   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.0216     0.0031     6.8740     0.0000      0.0154      0.0277
first_day_list_Signed up for lottery list on first day  2.815e-06     0.0050     0.0006     0.9995     -0.0097      0.0097
have_phone_list_Gave Phone Number                          0.0060     0.0041     1.4856     0.1374     -0.0019      0.0140
pobox_list_1: POBOX                                       -0.0181     0.0048    -3.8015     0.0001     -0.0275     -0.0088
self_list_Signed self up                                   0.0126     0.0036     3.5229     0.0004      0.0056      0.0196
female_list_1: Female                                     -0.0044     0.0036    -1.2043     0.2285     -0.0115      0.0028
numhh                                                     -0.0148     0.0025    -5.9399     0.0000     -0.0196     -0.0099
ohp_all_ever_matchn_30sep2009_Enrolled                    -0.0103     0.0131    -0.7828     0.4337     -0.0359      0.0154
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_depres_cens_ed
0.022309008985757828

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_mail_match_ed   R-squared:                      0.1040
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1030
No. Observations:                7236   F-statistic:                    693.22
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2114     0.0166     12.732     0.0000      0.1788      0.2439
first_day_list_Signed up for lottery list on first day     0.0543     0.0432     1.2575     0.2086     -0.0303      0.1389
have_phone_list_Gave Phone Number                          0.0370     0.0260     1.4257     0.1540     -0.0139      0.0879
pobox_list_1: POBOX                                       -0.0753     0.0650    -1.1596     0.2462     -0.2027      0.0520
self_list_Signed self up                                   0.0630     0.0233     2.6996     0.0069      0.0173      0.1088
female_list_1: Female                                      0.0108     0.0224     0.4842     0.6282     -0.0330      0.0547
numhh                                                     -0.0906     0.0202    -4.4747     0.0000     -0.1303     -0.0509
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0800     0.0716     1.1162     0.2643     -0.0604      0.2203
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_mail_match_ed
0.2245640903711319
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_inp_match_ed   R-squared:                      0.1310
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1303
No. Observations:               10157   F-statistic:                    1360.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.4966     0.0335     14.828     0.0000      0.4310      0.5622
first_day_list_Signed up for lottery list on first day     0.0873     0.0740     1.1801     0.2380     -0.0577      0.2323
have_phone_list_Gave Phone Number                          0.0809     0.0442     1.8295     0.0673     -0.0058      0.1675
pobox_list_1: POBOX                                       -0.3094     0.0625    -4.9472     0.0000     -0.4320     -0.1868
self_list_Signed self up                                   0.1270     0.0430     2.9515     0.0032      0.0427      0.2114
female_list_1: Female                                      0.0598     0.0377     1.5879     0.1123     -0.0140      0.1336
numhh                                                     -0.2295     0.0344    -6.6697     0.0000     -0.2969     -0.1620
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1715     0.1387     1.2369     0.2161     -0.1003      0.4433
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_inp_match_ed
0.5242058634757996

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:           charg_tot_ed   R-squared:                      0.0643
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0640
No. Observations:               24590   F-statistic:                    1423.4
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   2478.4     154.17     16.076     0.0000      2176.3      2780.6
first_day_list_Signed up for lottery list on first day     423.57     331.49     1.2778     0.2013     -226.14      1073.3
have_phone_list_Gave Phone Number                          239.59     228.28     1.0495     0.2939     -207.84      687.02
pobox_list_1: POBOX                                       -1315.9     361.65    -3.6385     0.0003     -2024.7     -607.05
self_list_Signed self up                                   1443.6     218.25     6.6143     0.0000      1015.8      1871.3
female_list_1: Female                                     -344.28     197.05    -1.7472     0.0806     -730.49      41.931
numhh                                                     -940.81     200.83    -4.6846     0.0000     -1334.4     -547.19
ohp_all_ever_matchn_30sep2009_Enrolled                     607.24     765.64     0.7931     0.4277     -893.38      2107.9
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
charg_tot_ed
2674.721435546875
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:        ed_charg_tot_ed   R-squared:                      0.1232
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1230
No. Observations:               24593   F-statistic:                    3087.5
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   1003.0     45.326     22.129     0.0000      914.19      1091.9
first_day_list_Signed up for lottery list on first day     212.79     96.380     2.2078     0.0273      23.884      401.69
have_phone_list_Gave Phone Number                          48.758     67.169     0.7259     0.4679     -82.890      180.41
pobox_list_1: POBOX                                       -390.55     119.21    -3.2762     0.0011     -624.19     -156.91
self_list_Signed self up                                   493.16     61.463     8.0237     0.0000      372.70      613.63
female_list_1: Female                                      29.342     53.786     0.5455     0.5854     -76.076      134.76
numhh                                                     -336.76     49.543    -6.7973     0.0000     -433.86     -239.66
ohp_all_ever_matchn_30sep2009_Enrolled                     248.25     206.43     1.2026     0.2291     -156.35      652.84
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
ed_charg_tot_ed
1130.5394287109375
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_hiun_cens_ed   R-squared:                      0.1372
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1370
No. Observations:               24593   F-statistic:                    3212.7
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.4412     0.0167     26.494     0.0000      0.4086      0.4739
first_day_list_Signed up for lottery list on first day     0.0157     0.0366     0.4286     0.6682     -0.0560      0.0873
have_phone_list_Gave Phone Number                          0.0431     0.0250     1.7261     0.0843     -0.0058      0.0921
pobox_list_1: POBOX                                       -0.1159     0.0573    -2.0237     0.0430     -0.2282     -0.0037
self_list_Signed self up                                   0.1475     0.0242     6.0877     0.0000      0.1000      0.1950
female_list_1: Female                                      0.0007     0.0213     0.0306     0.9756     -0.0411      0.0424
numhh                                                     -0.1846     0.0205    -9.0136     0.0000     -0.2247     -0.1444
ohp_all_ever_matchn_30sep2009_Enrolled                     0.2274     0.0835     2.7234     0.0065      0.0637      0.3910
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_hiun_cens_ed
0.4626210629940033
                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       num_loun_cens_ed   R-squared:                      0.1048
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1045
No. Observations:               24604   F-statistic:                    2432.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        09:38:05   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.3065     0.0153     20.098     0.0000      0.2766      0.3364
first_day_list_Signed up for lottery list on first day     0.0695     0.0323     2.1546     0.0312      0.0063      0.1327
have_phone_list_Gave Phone Number                          0.0197     0.0219     0.8988     0.3688     -0.0232      0.0626
pobox_list_1: POBOX                                       -0.1629     0.0444    -3.6678     0.0002     -0.2500     -0.0759
self_list_Signed self up                                   0.1148     0.0211     5.4392     0.0000      0.0734      0.1562
female_list_1: Female                                      0.0083     0.0181     0.4559     0.6485     -0.0272      0.0438
numhh                                                     -0.1006     0.0178    -5.6500     0.0000     -0.1355     -0.0657
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1754     0.0710     2.4707     0.0135      0.0362      0.3145
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
num_loun_cens_ed
0.346458375453949

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

In [126]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['any_visit_pre_ed_Yes']==0]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['any_visit_pre_ed_Yes']==0]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['any_visit_pre_ed_Yes']==0][others],instruments=ed_sample[ed_sample['any_visit_pre_ed_Yes']==0]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['any_visit_pre_ed_Yes']==0]['any_visit_ed_Yes'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.2490
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2487
No. Observations:               16930   F-statistic:                    5025.6
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        10:51:29   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.1441     0.0067     21.500     0.0000      0.1309      0.1572
first_day_list_Signed up for lottery list on first day     0.0164     0.0117     1.4014     0.1611     -0.0065      0.0393
have_phone_list_Gave Phone Number                          0.0494     0.0082     6.0266     0.0000      0.0333      0.0654
pobox_list_1: POBOX                                       -0.0357     0.0194    -1.8431     0.0653     -0.0736      0.0023
self_list_Signed self up                                   0.0519     0.0087     5.9501     0.0000      0.0348      0.0691
female_list_1: Female                                      0.0007     0.0067     0.1060     0.9155     -0.0124      0.0139
numhh                                                     -0.0185     0.0075    -2.4604     0.0139     -0.0332     -0.0038
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0832     0.0274     3.0413     0.0024      0.0296      0.1369
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.1988550768303706

<ipython-input-126-12603d361385>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['any_visit_pre_ed_Yes']==0]['any_visit_ed_Yes'].mean())

In [87]:

# Compte the average outcomes for different sample groups at different time periods.zhey
df_trend_0 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0]
df_trend_1 = ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==1]

Y_00 = df_trend_0['any_visit_pre_ed_Yes'].mean() # pre-treatment, control group
Y_10 = df_trend_1['any_visit_pre_ed_Yes'].mean() # pre-treatment, treatment group
Y_01 = df_trend_0['any_visit_ed_Yes'].mean() # post-treatment, control group
Y_11 = df_trend_1['any_visit_ed_Yes'].mean() # post-treatment, treatment group


# Compute the trend of each individual subject
df_trend_0['diff'] = df_trend_0['any_visit_ed_Yes'] - df_trend_0['any_visit_pre_ed_Yes'] 
df_trend_1['diff'] = df_trend_1['any_visit_ed_Yes'] - df_trend_1['any_visit_pre_ed_Yes']

<ipython-input-87-11593508c536>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_0['diff'] = df_trend_0['any_visit_ed_Yes'] - df_trend_0['any_visit_pre_ed_Yes']
<ipython-input-87-11593508c536>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_trend_1['diff'] = df_trend_1['any_visit_ed_Yes'] - df_trend_1['any_visit_pre_ed_Yes']

In [125]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']==1][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==1]['any_visit_ed_Yes'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.4899
Estimator:                    IV-2SLS   Adj. R-squared:                 0.4889
No. Observations:                3880   F-statistic:                    3635.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        10:51:16   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.2222     0.0256     8.6679     0.0000      0.1720      0.2725
first_day_list_Signed up for lottery list on first day     0.0362     0.0261     1.3872     0.1654     -0.0150      0.0874
have_phone_list_Gave Phone Number                          0.0330     0.0218     1.5156     0.1296     -0.0097      0.0757
pobox_list_1: POBOX                                       -0.0843     0.0489    -1.7255     0.0844     -0.1801      0.0115
self_list_Signed self up                                   0.2004     0.0285     7.0363     0.0000      0.1445      0.2562
female_list_1: Female                                      0.0193     0.0171     1.1288     0.2590     -0.0142      0.0528
numhh                                                      0.0304     0.0236     1.2915     0.1965     -0.0158      0.0766
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1207     0.0596     2.0250     0.0429      0.0039      0.2375
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.43069833392414036

<ipython-input-125-7074aa310852>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==1]['any_visit_ed_Yes'].mean())

In [128]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.6772
Estimator:                    IV-2SLS   Adj. R-squared:                 0.6763
No. Observations:                2874   F-statistic:                    6087.8
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        10:54:28   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.3387     0.0374     9.0563     0.0000      0.2654      0.4120
first_day_list_Signed up for lottery list on first day     0.0356     0.0293     1.2169     0.2236     -0.0218      0.0930
have_phone_list_Gave Phone Number                          0.0661     0.0246     2.6906     0.0071      0.0180      0.1143
pobox_list_1: POBOX                                       -0.1342     0.0583    -2.3024     0.0213     -0.2484     -0.0200
self_list_Signed self up                                   0.2400     0.0406     5.9150     0.0000      0.1605      0.3195
female_list_1: Female                                      0.0203     0.0184     1.1013     0.2708     -0.0158      0.0564
numhh                                                      0.0920     0.0315     2.9192     0.0035      0.0302      0.1538
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1163     0.0655     1.7754     0.0758     -0.0121      0.2446
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.6348733233979136

<ipython-input-128-d921bc8ffc30>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
<ipython-input-128-d921bc8ffc30>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
<ipython-input-128-d921bc8ffc30>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
<ipython-input-128-d921bc8ffc30>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
<ipython-input-128-d921bc8ffc30>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'].mean())
<ipython-input-128-d921bc8ffc30>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['any_visit_ed_Yes'].mean())

In [129]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=5]['any_visit_ed_Yes'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.8924
Estimator:                    IV-2SLS   Adj. R-squared:                 0.8914
No. Observations:                 921   F-statistic:                    8375.5
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        10:55:56   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.4208     0.0882     4.7714     0.0000      0.2480      0.5937
first_day_list_Signed up for lottery list on first day    -0.0194     0.0345    -0.5609     0.5749     -0.0870      0.0483
have_phone_list_Gave Phone Number                          0.0206     0.0261     0.7893     0.4300     -0.0305      0.0716
pobox_list_1: POBOX                                       -0.1163     0.0836    -1.3913     0.1641     -0.2802      0.0476
self_list_Signed self up                                   0.4456     0.0874     5.0978     0.0000      0.2743      0.6169
female_list_1: Female                                      0.0305     0.0264     1.1543     0.2484     -0.0213      0.0822
numhh                                                      0.1049     0.0485     2.1632     0.0305      0.0099      0.2000
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0108     0.0861     0.1251     0.9004     -0.1580      0.1795
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.8676975945017182

<ipython-input-129-ffbe97af3f24>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=5]['any_visit_ed_Yes'].mean())

In [131]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_out_cens_ed']>=2]['any_visit_ed_Yes'],endog = ed_sample[ed_sample['num_out_cens_ed']>=2]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_out_cens_ed']>=2][others],instruments=ed_sample[ed_sample['num_out_cens_ed']>=2]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_out_cens_ed']>=2]['any_visit_ed_Yes'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed_Yes   R-squared:                      0.9853
Estimator:                    IV-2SLS   Adj. R-squared:                 0.9853
No. Observations:                4126   F-statistic:                  1.11e+06
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        10:58:55   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.3904     0.0191     20.396     0.0000      0.3529      0.4279
first_day_list_Signed up for lottery list on first day    -0.0081     0.0061    -1.3332     0.1825     -0.0199      0.0038
have_phone_list_Gave Phone Number                          0.1067     0.0070     15.190     0.0000      0.0930      0.1205
pobox_list_1: POBOX                                        0.0163     0.0117     1.3976     0.1622     -0.0066      0.0392
self_list_Signed self up                                   0.4819     0.0179     26.994     0.0000      0.4469      0.5168
female_list_1: Female                                      0.0091     0.0039     2.3291     0.0199      0.0014      0.0168
numhh                                                      0.2402     0.0133     18.038     0.0000      0.2141      0.2663
ohp_all_ever_matchn_30sep2009_Enrolled                     0.0755     0.0133     5.6644     0.0000      0.0494      0.1016
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
1.0

<ipython-input-131-6dfd81cbc3a2>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_out_cens_ed']>=2]['any_visit_ed_Yes'].mean())

In [132]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']==0]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']==0]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']==0][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']==0]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==0]['num_visit_cens_ed'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.1423
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1419
No. Observations:               16930   F-statistic:                    2374.2
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        11:17:06   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.3072     0.0161     19.061     0.0000      0.2756      0.3388
first_day_list_Signed up for lottery list on first day     0.0362     0.0333     1.0871     0.2770     -0.0290      0.1013
have_phone_list_Gave Phone Number                          0.0835     0.0226     3.6868     0.0002      0.0391      0.1278
pobox_list_1: POBOX                                       -0.0558     0.0494    -1.1308     0.2582     -0.1526      0.0409
self_list_Signed self up                                   0.0838     0.0219     3.8176     0.0001      0.0408      0.1268
female_list_1: Female                                     -0.0348     0.0190    -1.8316     0.0670     -0.0721      0.0024
numhh                                                     -0.0953     0.0181    -5.2594     0.0000     -0.1308     -0.0598
ohp_all_ever_matchn_30sep2009_Enrolled                     0.2758     0.0792     3.4838     0.0005      0.1206      0.4310
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.3559807240962982

<ipython-input-132-0b66b2fc6c21>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==0]['num_visit_cens_ed'].mean())

In [133]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']==1][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']==1]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==1]['num_visit_cens_ed'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.2693
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2677
No. Observations:                3880   F-statistic:                    1313.4
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        11:18:47   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   0.5781     0.0815     7.0923     0.0000      0.4184      0.7379
first_day_list_Signed up for lottery list on first day     0.0551     0.1032     0.5341     0.5933     -0.1471      0.2573
have_phone_list_Gave Phone Number                          0.0994     0.0815     1.2190     0.2229     -0.0604      0.2592
pobox_list_1: POBOX                                       -0.3201     0.1398    -2.2896     0.0220     -0.5942     -0.0461
self_list_Signed self up                                   0.3864     0.0961     4.0199     0.0001      0.1980      0.5749
female_list_1: Female                                      0.0114     0.0700     0.1628     0.8706     -0.1258      0.1486
numhh                                                     -0.0981     0.0811    -1.2085     0.2269     -0.2571      0.0610
ohp_all_ever_matchn_30sep2009_Enrolled                     0.6805     0.2487     2.7359     0.0062      0.1930      1.1681
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
0.9854661226272583

<ipython-input-133-46cee2a2fd03>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']==1]['num_visit_cens_ed'].mean())

In [134]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.3690
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3672
No. Observations:                2871   F-statistic:                    1679.6
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        11:20:45   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   1.4700     0.1972     7.4544     0.0000      1.0835      1.8564
first_day_list_Signed up for lottery list on first day     0.0698     0.1855     0.3762     0.7067     -0.2938      0.4334
have_phone_list_Gave Phone Number                          0.1183     0.1586     0.7459     0.4557     -0.1925      0.4292
pobox_list_1: POBOX                                       -0.7964     0.2885    -2.7600     0.0058     -1.3619     -0.2308
self_list_Signed self up                                   0.7711     0.2249     3.4285     0.0006      0.3303      1.2119
female_list_1: Female                                     -0.0476     0.1197    -0.3977     0.6909     -0.2823      0.1870
numhh                                                     -0.0114     0.1597    -0.0712     0.9432     -0.3244      0.3016
ohp_all_ever_matchn_30sep2009_Enrolled                     0.1617     0.4195     0.3855     0.6999     -0.6604      0.9838
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
2.0775346755981445

<ipython-input-134-8cf898909566>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
<ipython-input-134-8cf898909566>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
<ipython-input-134-8cf898909566>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
<ipython-input-134-8cf898909566>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['treatment_Selected'])
/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
<ipython-input-134-8cf898909566>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'].mean())
<ipython-input-134-8cf898909566>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=2][ed_sample['num_visit_pre_cens_ed']<=4]['num_visit_cens_ed'].mean())

In [135]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_visit_pre_cens_ed']>=5][others],instruments=ed_sample[ed_sample['num_visit_pre_cens_ed']>=5]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=5]['num_visit_cens_ed'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.5338
Estimator:                    IV-2SLS   Adj. R-squared:                 0.5297
No. Observations:                 910   F-statistic:                    1053.9
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        11:22:32   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   2.1171     1.2311     1.7196     0.0855     -0.2959      4.5300
first_day_list_Signed up for lottery list on first day     0.3121     0.6446     0.4843     0.6282     -0.9512      1.5755
have_phone_list_Gave Phone Number                          0.9443     0.5048     1.8705     0.0614     -0.0451      1.9337
pobox_list_1: POBOX                                       -0.2755     1.4005    -0.1967     0.8441     -3.0204      2.4694
self_list_Signed self up                                   2.7643     1.2049     2.2942     0.0218      0.4028      5.1259
female_list_1: Female                                     -0.0805     0.5164    -0.1558     0.8762     -1.0927      0.9318
numhh                                                     -0.2078     0.6836    -0.3040     0.7611     -1.5476      1.1319
ohp_all_ever_matchn_30sep2009_Enrolled                     2.6002     1.7073     1.5230     0.1278     -0.7461      5.9466
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
5.941277980804443

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
<ipython-input-135-e77b5626545e>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_visit_pre_cens_ed']>=5]['num_visit_cens_ed'].mean())

In [136]:
IV_model = IV2SLS(dependent = ed_sample[ed_sample['num_out_cens_ed']>=2]['num_visit_cens_ed'],endog = ed_sample[ed_sample['num_out_cens_ed']>=2]['ohp_all_ever_matchn_30sep2009_Enrolled'],\
                  exog = ed_sample[ed_sample['num_out_cens_ed']>=2][others],instruments=ed_sample[ed_sample['num_out_cens_ed']>=2]['treatment_Selected'])
res_2sls = IV_model.fit()
print(res_2sls)
print(var)
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_out_cens_ed']>=2]['num_visit_cens_ed'].mean())

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.5832
Estimator:                    IV-2SLS   Adj. R-squared:                 0.5824
No. Observations:                4125   F-statistic:                    5822.2
Date:                Thu, May 20 2021   P-value (F-stat)                0.0000
Time:                        11:23:54   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                                   Parameter Estimates
==========================================================================================================================
                                                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------------------
english_list_Requested English materials                   2.3019     0.2244     10.258     0.0000      1.8621      2.7417
first_day_list_Signed up for lottery list on first day    -0.0781     0.1942    -0.4022     0.6875     -0.4586      0.3024
have_phone_list_Gave Phone Number                          0.2987     0.1686     1.7720     0.0764     -0.0317      0.6292
pobox_list_1: POBOX                                       -0.2203     0.3907    -0.5638     0.5729     -0.9860      0.5455
self_list_Signed self up                                   1.9901     0.2428     8.1950     0.0000      1.5141      2.4660
female_list_1: Female                                     -0.0312     0.1363    -0.2286     0.8192     -0.2983      0.2360
numhh                                                      0.1141     0.1765     0.6464     0.5180     -0.2319      0.4601
ohp_all_ever_matchn_30sep2009_Enrolled                     0.6834     0.4254     1.6063     0.1082     -0.1504      1.5173
==========================================================================================================================

Endogenous: ohp_all_ever_matchn_30sep2009_Enrolled
Instruments: treatment_Selected
Robust Covariance (Heteroskedastic)
Debiased: False
any_visit_ed_Yes
4.472900867462158

/Users/anaconda3/lib/python3.8/site-packages/linearmodels/shared/exceptions.py:35: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)
<ipython-input-136-65e79c322c2b>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][ed_sample['num_out_cens_ed']>=2]['num_visit_cens_ed'].mean())

In [25]:
for var in outcome_vars_val_ed:
    print(var, ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0][var].std())

num_visit_cens_ed 2.1351544857025146
num_hosp_cens_ed 0.44860321283340454
num_out_cens_ed 1.9650274515151978
num_on_cens_ed 1.2974438667297363
num_off_cens_ed 1.1599416732788086
num_edcnnp_ed 0.6385219693183899
num_edcnpa_ed 0.30985787510871887
num_epct_ed 0.8649779558181763
num_ne_ed 0.609429121017456
num_unclas_ed 0.6090102195739746
num_acsc_cens_ed 0.3248712420463562
num_chron_cens_ed 0.6993204355239868
num_inj_cens_ed 0.841819703578949
num_skin_cens_ed 0.32977861166000366
num_abdo_cens_ed 0.27028512954711914
num_back_cens_ed 0.26699432730674744
num_heart_cens_ed 0.20980949699878693
num_head_cens_ed 0.22318696975708008
num_depres_cens_ed 0.24563738703727722
num_mail_match_ed 0.8002269864082336
num_inp_match_ed 1.5768836736679077
charg_tot_ed 11966.7412109375
ed_charg_tot_ed 3671.3837890625
num_hiun_cens_ed 1.4239410161972046
num_loun_cens_ed 1.1924586296081543

In [32]:
print(ed_sample[ed_sample['ohp_all_ever_matchn_30sep2009_Enrolled']==0]['num_visit_cens_ed'].std())

2.1351544857025146